'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Translation System Structure
 * 
 * This file contains all UI translations for Banda Chao in three languages:
 * - zh: Simplified Chinese (简体中文) - for mainland China users
 * - ar: Arabic (العربية) - for Arabic-speaking users
 * - en: English - default/fallback language
 * 
 * Usage:
 * - Use `useLanguage()` hook to access translations
 * - Call `t('key')` to get translated string
 * - Founder Dashboard pages use hardcoded Arabic strings (not from this translation system)
 * 
 * Adding new keys:
 * 1. Add the key to all three language objects (zh, ar, en)
 * 2. Use descriptive, camelCase keys like 'productDetailAddToCart'
 * 3. Keep translations natural and context-appropriate
 */

// Translations
const translations: Record<Language, Record<string, string>> = {
  zh: {
    'home': '首页',
    'shortVideos': '短视频',
    'longVideos': '长视频',
    'products': '商品',
    'search': '搜索',
    'chat': '聊天',
    'feed': '动态',
    'uploadVideo': '上传视频',
    'addProduct': '添加商品',
    'login': '登录',
    'register': '注册',
    'logout': '退出',
    'myAccount': '我的账户',
    'loading': '加载中...',
    'error': '错误',
    'retry': '重试',
    'noContent': '暂无内容',
    'viewMore': '查看更多',
    'welcome': '欢迎来到 Banda Chao',
    'subtitle': '结合社交媒体与电子商务的创新平台',
    'subtitle2': '分享视频，展示产品，连接世界',
    'watchShortVideos': '观看短视频',
    'browseProducts': '浏览商品',
    'hotShortVideos': '热门短视频',
    'featuredLongVideos': '精选长视频',
    'recommendedProducts': '推荐商品',
    'language': '语言',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': '为世界上的创作者打造的中立平台',
    'footerDescription': '一个连接全球手作人与买家的社交电商平台，用公平、温暖与智能，让每一件手作都找到懂它的人。',
    'about': '关于 Banda Chao',
    'aboutDescription': '一个连接全球手作人与买家的社交电商平台，用公平、温暖与智能，让每一件手作都找到懂它的人。',
    'aboutUs': '关于我们',
    'allRightsReserved': '保留所有权利。',
    'videos': '视频',
    'community': '社区',
    'makers': '手作人',
    'orders': '订单',
    'discover': '探索',
    'aboutPandaChao': '关于 Banda Chao',
    'whySell': '为什么选择我们？',
    'creatorStories': '创作者故事',
    'faq': '常见问题',
    'communityServices': '社区与服务',
    'servicesMarketplace': '服务市场',
    'becomeServiceProvider': '成为服务提供者',
    'blog': '博客',
    'contact': '联系我们',
    'toolsLanguages': '工具与语言',
    'languageSwitcher': '切换语言',
    'currencySwitcher': '货币',
    'appComingSoon': '应用商店图标即将上线',
    'rightsReserved': '© 2025 Banda Chao. 保留所有权利。',
    'terms': '使用条款',
    'privacy': '隐私政策',
    'homeHeroHeadline': 'Banda Chao —— 全球手作人的温暖之家',
    'homeHeroDescription': '在 Banda Chao，来自中国、阿拉伯地区和世界各地的手作人，都能将原创好物带给真正懂得欣赏的买家。这里有公平透明的交易环境、温暖友好的社区氛围，还有智能 AI 熊猫助手一路相伴。让每一件作品都被看见，让每一位匠人都被尊重。',
    'homeHeroTitle': 'Banda Chao —— 全球手作人的温暖之家',
    'homeHeroCTA': '开始逛逛',
    'watchVideos': '开始逛逛',
    'featuredMakers': '本周精选匠人',
    'featuredProducts': '社区最新上架',
    'featuredVideos': '精选视频',
    'viewAll': '查看更多',
    'viewAllMakers': '查看更多手作人',
    'founderSectionTitle': '创始人控制中心',
    'founderSectionDescription': '为创始人：6个专业AI助手帮助您进行战略决策、技术、安全、商务、内容和物流。',
    'goToFounderConsole': '前往创始人控制台',
    'previous': '上一页',
    'allCategories': '全部',
    'decreaseQuantity': '减少数量',
    'increaseQuantity': '增加数量',
    'makerSince': '自',
    'makerUnfollowButton': '取消关注',
    'noStoryYet': '还没有分享故事',
    'noProductsYet': '还没有添加产品',
    'noVideosYet': '还没有上传视频',
    'viewAllProducts': '查看所有产品',
    'viewAllVideos': '查看所有视频',
    'exploreMakers': '探索手作人',
    'discoverTalentedMakers': '发现才华横溢的手作人及其独特作品',
    'searchMakers': '搜索手作人...',
    'loadingMakers': '加载手作人...',
    'noMakersFound': '没有找到手作人',
    'tryDifferentSearch': '试试其他关键词，或者调整筛选条件',
    'clearFilters': '清除过滤器',
    'showing': '显示',
    'of': '的',
    'location': '位置',
    'allLocations': '所有位置',
    'noProductsInCategory': '此分类暂无商品',
    'noProductsDescription': '暂时还没有商品哦，稍后再来看看吧',
    'noMakersDescription': '暂时还没有手作人，很快就有了',
    'noVideosDescription': '暂时还没有视频，很快就有了',
    'unexpectedError': '出了点小状况，请稍后再试',
    'backToHome': '返回首页',
    'myVideos': '我的视频',
    'myProducts': '我的产品',
    'uploadYourFirstVideo': '上传你的第一个视频，分享你的创作故事',
    'addYourFirstProduct': '添加你的第一个产品，让更多人看到你的作品',
    'priceTBD': '价格待定',
    'views': '观看',
    'uploadShortVideo': '上传短视频',
    'uploadLongVideo': '上传长视频',
    'shortVideoDescription': '最长 60 秒，快速展示作品亮点，吸引买家关注',
    'longVideoDescription': '最长 10 分钟，完整呈现制作过程和背后的故事',
    'makerDashboard': '手作人控制台',
    'manageYourMakerProfile': '管理你的手作人档案和内容。',
    'viewPublicProfile': '查看公开档案',
    'editProfile': '编辑档案',
    'editMakerProfile': '编辑手作人档案',
    'notRegisteredAsMaker': '你还没有创建手作人档案',
    'becomeMakerDescription': '创建你的手作人档案，分享你的创作故事，与来自世界各地的买家建立温暖的连接。',
    'becomeMaker': '成为手作人',
    'createMakerProfile': '创建手作人档案',
    'makerOnboardingChecklist': '手作人入门清单',
    'makerOnboardingChecklistDesc': '完成以下任务，开启你的手作人旅程',
    'makerRequirementProfile': '完成个人资料信息',
    'makerRequirementProfileDesc': '添加您的姓名和简短简介',
    'makerRequirementFirstProduct': '添加第一个产品',
    'makerRequirementFirstProductDesc': '添加您的第一个产品以显示在您的商店中',
    'makerRequirementFirstVideo': '添加第一个视频',
    'makerRequirementFirstVideoDesc': '分享一个展示您技能或产品的视频',
    'makerRequirementProfilePicture': '添加个人资料图片',
    'makerRequirementProfilePictureDesc': '为您的个人资料添加图片',
    'makerRequirementStory': '添加制造商故事',
    'makerRequirementStoryDesc': '分享您的工艺故事（至少50个字符）',
    'makerReadyToGoLive': '准备上线！',
    'makerReadyToGoLiveDesc': '太棒了！你已经完成了所有任务，商店已准备好向买家展示啦',
    'makerAlmostReady': '您几乎准备好了！',
    'makerAlmostReadyDesc': '再完成几个任务，就能让你的档案更完整',
    'makerNotReady': '尚未准备好',
    'makerNotReadyDesc': '至少完成 3 个任务，就能开始销售了',
    'completed': '已完成',
    'progress': '进度',
    'completeNow': '立即完成',
    'addPicture': '添加图片',
    'addStory': '添加故事',
    'nameRequired': '名称是必需的',
    'makerCreatedSuccess': '手作人档案创建成功！',
    'createMakerFailed': '创建手作人档案失败',
    'makerUpdatedSuccess': '手作人档案更新成功！',
    'updateMakerFailed': '更新手作人档案失败',
    'saving': '保存中...',
    'saveChanges': '保存更改',
    'creating': '创建中...',
    'create': '创建',
    'totalVideos': '总视频数',
    'totalProducts': '总商品数',
    'totalViews': '总浏览量',
    'totalLikes': '总点赞数',
    'pillar1Title': '对手作人更公平',
    'pillar1Body': '透明合理的收费，让每一件作品的价值都被真实认可。',
    'pillar2Title': '让买家更安心',
    'pillar2Body': '认证手作人、真实物流信息、多重保障，让每次购买都值得信赖。',
    'pillar3Title': 'AI 熊猫与你同行',
    'pillar3Body': '贴心的 AI 熊猫助手，为创作者和买家提供语言翻译、运营建议和成长陪伴。',
    'founderCommandCenter': '创始人控制中心',
    'founderHeroDescription': '在 Banda Chao，您拥有6个专业AI助手，帮助您处理：',
    'founderAssistantsList': '战略决策、技术、安全、商务、内容和物流',
    'totalUsers': '总用户数',
    'totalMakers': '总手作人数',
    'goToAssistantsCenter': '前往助手中心',
    'founderOnlyAccess': '仅限FOUNDER角色访问',
    'yourSixAssistants': '您的六个助手',
    'eachAssistantSpecialized': '每个助手都专注于自己的领域，帮助您做出更好的决策',
    'quickLinks': '快速链接',
    'gettingStartedTitle': '欢迎来到 Banda Chao！',
    'gettingStartedDescription': '了解如何充分利用这个平台：发现手作人、浏览商品、观看视频，并关注你喜欢的创作者。',
    'onboardingStep1Title': '什么是 Banda Chao？',
    'onboardingStep1Description': 'Banda Chao 是独立手作人的温暖之家，让热爱手作的买家能轻松找到真正有温度的作品。',
    'onboardingStep2Title': '对手作人更公平',
    'onboardingStep2Description': '透明合理的抽成、简单易用的定价工具，帮助手作人以公平的价格，把作品带到全世界。',
    'onboardingStep3Title': '让买家更安心',
    'onboardingStep3Description': '真实可验证的手作人档案、清晰的运费与物流信息，完善的买家保障，让每一次跨境购物都更放心。',
    'onboardingStep4Title': 'AI 熊猫与你同行',
    'onboardingStep4Description': '贴心的 AI 熊猫助手，为你提供多语言翻译、运营建议和成长陪伴，让每一步都更轻松。',
    'skip': '跳过',
    'getStarted': '立即开始',
    'next': '下一步',
    'close': '关闭',
    'makersPage': '手作人页面',
    'exploreRegisteredMakers': '探索平台上注册的手作人',
    'contentAndVideos': '内容和视频',
    'browseVideosAndProducts': '浏览添加的视频和产品',
    'reviewNotificationsAndControl': '查看通知和控制中心',
    'featuredMakersTitle': '本周精选匠人',
    'featuredMakerName1': '陈素素',
    'featuredMakerBio1': '来自云南山区的手工艺人，以天然植物染织手工披肩。',
    'featuredMakerName2': '王小梅',
    'featuredMakerBio2': '将传统陶艺与现代审美结合，打造温润的日常茶具。',
    'featuredMakerName3': '刘海涛',
    'featuredMakerBio3': '竹编第四代传承人，创作可持续的生活家居。',
    'latestProductsTitle': '社区最新上架',
    'mockProductName1': '匠心茶具套装',
    'mockProductDescription1': '手工拉坯烧制的茶具，适合日常品茗与待客。',
    'mockProductCategory1': '茶具',
    'mockProductName2': '手织藤编托特包',
    'mockProductDescription2': '轻盈又结实的手工托特包，带来自然气息。',
    'mockProductCategory2': '配饰',
    'mockProductName3': '竹制静夜台灯',
    'mockProductDescription3': '柔和灯光配合竹编纹理，营造温暖空间。',
    'mockProductCategory3': '家居',
    'mockProductName4': '手绘陶瓷茶杯',
    'mockProductDescription4': '每只杯子都带有独特的手绘图案，适合收藏。',
    'mockProductCategory4': '陶瓷',
    'howItWorksTitle': '发现・连接・支持',
    'howItWorksStep1Title': '1. 发现真实故事',
    'howItWorksStep1Description': '深入了解手作人的创作故事与灵感来源，感受每件作品背后的温度。',
    'howItWorksStep2Title': '2. 直接对话手作人',
    'howItWorksStep2Description': '通过平台与手作人直接交流，提出定制需求或分享合作想法。',
    'howItWorksStep3Title': '3. 支持可持续创作',
    'howItWorksStep3Description': '购买带着温度的作品，让手作人能持续创作更多美好的事物。',
    'ctaHeadline': '你也是手作人吗？加入我们，一起创造温暖',
    'ctaButtonText': '我要开店',
    'productsPageTitle': '全部商品',
    'productsFilterCategoriesTitle': '分类',
    'productsFilterCategoryApparel': '服饰',
    'productsFilterCategoryHomeDecor': '家居装饰',
    'productsFilterCategoryAccessories': '配饰',
    'productsFilterPriceTitle': '价格区间',
    'productsFilterPricePlaceholder': '价格滑块即将上线',
    'productsFilterMakersTitle': '匠人',
    'productsFilterMakerA': '匠人 A',
    'productsFilterMakerB': '匠人 B',
    'productsFilterMakerC': '匠人 C',
    'productDetailBy': '来自',
    'productDetailPlaceholderMaker': '手工匠人 李娜',
    'productDetailPlaceholderTitle': '手工编织竹制灯具',
    'productDetailPlaceholderPrice': '¥329',
    'productDetailQuantity': '数量',
    'productDetailAddToCart': '加入购物车',
    'buyNow': '立即购买',
    'shipping': '配送',
    'productDescription': '商品详情',
    'similarProducts': '猜你喜欢',
    'aboutThisMaker': '关于这位手作人',
    'moreFromThisMaker': '更多来自这位手作人',
    'profile': '个人中心',
    'itemsCount': '{count} 件商品',
    'loadingFounderConsole': '正在加载创始人控制台...',
    'loadingNotifications': '加载通知中...',
    'noNotifications': '还没有通知',
    'notifications': '通知',
    'productId': '产品ID',
    'founderConsole': '创始人控制台',
    'founderAccount': '创始人账户',
    'founder': '创始人',
    'feedComingSoon': '创作者动态（即将推出）',
    'feedComingSoonDescription': '全球手作人和买家的社交动态即将上线，这里将成为我们社交电商平台的核心',
    'feedShortVideosDescription': '通过精彩的短视频，发现手作人背后的故事和作品的独特魅力',
    'feedSocialCommerceDescription': '直接在动态中购买，支持来自中国、阿拉伯和西方的优秀手作人',
    'feedGlobalCommunityDescription': '在中立、安全的空间中，与三种文化的手作人和买家温暖连接',
    'developmentInProgress': '开发中...',
    'markAllAsRead': '全部标记为已读',
    'totalNotifications': '总通知数：{total}',
    'loadMore': '加载更多',
    'justNow': '刚刚',
    'minutesAgo': '{minutes} 分钟前',
    'hoursAgo': '{hours} 小时前',
    'daysAgo': '{days} 天前',
    'socialCommerce': '社交电商',
    'globalCommunity': '全球社区',
    'productDetailStoryTitle': '作品故事',
    'productDetailStoryParagraph1': '这件作品来自云南山区的匠人李娜，融合传统竹编技艺与现代生活美学。每一道纹理都由手工完成，保持竹材的自然韵味。',
    'productDetailStoryParagraph2': '制作过程中，匠人会精心挑选竹材，进行清洗、晾晒和蒸汽定型，确保灯具在使用时稳定耐用，同时保留竹材的原色。',
    'productDetailStoryParagraph3': '灯光透过竹编的纹理，在夜晚为空间带来温暖而宁静的光影，适合放置在卧室、书房或客厅角落，营造舒缓氛围。',
    'makerCoverAlt': '匠人主页封面图',
    'makerProfilePlaceholderName': '张伟',
    'makerProfilePlaceholderBio': '来自云南的木工匠人，用温暖木纹讲述家的故事。',
    'makerFollowButton': '关注',
    'makerStoryTitle': '我的故事',
    'makerStoryParagraph1': '我出生在云南的一个小山村，从小跟随外公学习木工。木头的纹理就像自然写下的诗，每一件作品都有独特的生命力。',
    'makerStoryParagraph2': '为了寻找最适合的木材，我常常深入山林，与当地村民交流，确保每块木头都来自可持续来源。制作过程中，我坚持手工打磨，只为保留木头的温润触感。',
    'makerStoryParagraph3': '我希望通过这些作品，让更多人感受到慢生活的温度，也希望支持更多年轻人加入到手工匠人的队伍中。',
    'makerCreationsTitle': '我的作品',
    // Register page translations
    'registerTitle': '创建新账户',
    'registerSubtitle': '已有账户？',
    'registerLoginLink': '登录',
    'registerNameLabel': '姓名（可选）',
    'registerNamePlaceholder': '您的姓名',
    'registerEmailLabel': '电子邮箱',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': '密码',
    'registerPasswordPlaceholder': '至少6个字符',
    'registerConfirmPasswordLabel': '确认密码',
    'registerConfirmPasswordPlaceholder': '请再次输入密码',
    'registerButton': '创建账户',
    'registerButtonLoading': '注册中...',
    'registerButtonSuccess': '注册成功！',
    'registerSuccessMessage': '账户创建成功！正在跳转...',
    'registerPasswordMismatch': '密码不匹配',
    'registerPasswordTooShort': '密码至少需要6个字符',
    'registerEmailInvalid': '请输入有效的电子邮箱地址',
    'registerNameTooShort': '姓名至少需要2个字符',
    'registerError': '注册遇到问题，请稍后再试',
    'registerGoogleError': 'Google 登录遇到问题，请重试',
    'registerOr': '或',
    'registerGoogleButton': '使用Google注册',
    'loginTitle': '登录',
    'loginSubtitle': '还没有账户？',
    'loginEmailLabel': '电子邮箱',
    'loginEmailPlaceholder': 'example@email.com',
    'loginPasswordLabel': '密码',
    'loginPasswordPlaceholder': '请输入密码',
    'loginButton': '登录',
    'loginButtonLoading': '登录中...',
    'loginGoogleButton': '使用Google登录',
    'loginOr': '或',
    'loginError': '登录遇到问题，请检查邮箱和密码后重试',
    'loginSuccess': '登录成功！正在跳转...',
    'myOrders': '我的订单',
    'myOrdersSubtitle': '查看所有订单并跟踪状态',
    'orderStatusPending': '待处理',
    'orderStatusProcessing': '处理中',
    'orderStatusShipped': '已发货',
    'orderStatusDelivered': '已送达',
    'orderStatusCancelled': '已取消',
    'orderStatusFailed': '失败',
    'orderTotal': '订单总额',
    'orderDate': '订单日期',
    'orderItems': '订单商品',
    'orderShippingAddress': '收货地址',
    'noOrdersYet': '还没有订单',
    'noOrdersDescription': '还没有订单呢，快去逛逛，发现心仪的好物吧',
    'cart': '购物车',
    'cartEmpty': '购物车还是空的',
    'cartEmptyDescription': '去逛逛，把喜欢的好物加入购物车吧',
    'checkout': '结账',
    'checkoutTitle': '结账',
    'checkoutShippingInfo': '收货信息',
    'checkoutPayment': '支付',
    'checkoutPlaceOrder': '提交订单',
    'checkoutCartInvalid': '购物车中的部分商品已失效，请刷新后重试',
    'checkoutPhoneInvalid': '请输入正确的电话号码',
    'checkoutErrorGeneric': '订单创建失败，请稍后再试',
    'checkoutErrorValidation': '订单信息有误，请检查购物车和收货地址',
    'checkoutErrorAuth': '请先登录后再下单',
    'checkoutErrorForbidden': '抱歉，你没有权限创建此订单',
    'checkoutErrorConflict': '订单信息冲突，请刷新页面后重试',
    'checkoutErrorServer': '服务器暂时出问题了，请稍后再试',
    'checkoutFormInvalid': '请填写完整的收货信息',
    'processingPayment': '处理中...',
    'proceedToPayment': '前往支付',
    'loadOrdersFailed': '加载订单失败',
    'minPrice': '最低价',
    'maxPrice': '最高价',
    'to': '至',
    'clearPriceFilter': '清除价格筛选',
    'noCategories': '暂无分类',
    'activeFilters': '已选筛选',
    'videoTitle': '标题',
    'videoDescription': '描述',
    'videoTitlePlaceholder': '输入视频标题',
    'videoDescriptionPlaceholder': '描述您的视频...',
    'videoFile': '视频文件',
    'thumbnail': '缩略图',
    'selectVideoFile': '点击选择视频文件',
    'selectThumbnail': '点击选择缩略图',
    'videoType': '视频类型',
    'maxDurationShort': '最多60秒',
    'maxDurationLong': '最多10分钟',
    'duration': '时长',
    'selectVideoFileError': '请选择视频文件',
    'selectImageFileError': '请选择图片文件',
    'pleaseLogin': '请先登录',
    'selectVideoAndThumbnail': '请选择视频和缩略图',
    'enterVideoTitle': '请输入视频标题',
    'cannotGetDuration': '无法获取视频时长',
    'shortVideoMaxDuration': '短视频不能超过60秒',
    'longVideoMaxDuration': '长视频不能超过10分钟',
    'uploadFailed': '上传失败',
    'uploading': '上传中...',
    'cancel': '取消',
    'linkProducts': '关联产品 (可选)',
    'selectedProductsCount': '已选择 {count} 个产品',
    'loadingFilterOptions': '加载筛选选项...',
  },
  ar: {
    'home': 'الرئيسية',
    'shortVideos': 'فيديوهات قصيرة',
    'longVideos': 'فيديوهات طويلة',
    'products': 'المنتجات',
    'search': 'البحث',
    'chat': 'الدردشة',
    'feed': 'المنشورات',
    'uploadVideo': 'رفع فيديو',
    'addProduct': 'إضافة منتج',
    'login': 'تسجيل الدخول',
    'register': 'التسجيل',
    'logout': 'تسجيل الخروج',
    'myAccount': 'حسابي',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'retry': 'إعادة المحاولة',
    'noContent': 'لا يوجد محتوى',
    'viewMore': 'عرض المزيد',
    'welcome': 'مرحباً بك في Panda Chao',
    'subtitle': 'منصة مبتكرة تجمع بين التواصل الاجتماعي والتجارة الإلكترونية',
    'subtitle2': 'شارك الفيديوهات، اعرض المنتجات، واتصل بالعالم',
    'watchShortVideos': 'مشاهدة الفيديوهات القصيرة',
    'browseProducts': 'تصفح المنتجات',
    'hotShortVideos': 'الفيديوهات القصيرة الشائعة',
    'featuredLongVideos': 'الفيديوهات الطويلة المميزة',
    'recommendedProducts': 'المنتجات الموصى بها',
    'language': 'اللغة',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'منصة محايدة لدعم صنّاع المحتوى حول العالم',
    'footerDescription': 'منصة اجتماعية-تجارية تربط الحرفيين بالمشترين حول العالم، وتعزز العدالة، الثقة، والذكاء في التجارة الإبداعية.',
    'about': 'عن باندتشاو',
    'aboutDescription': 'منصة اجتماعية-تجارية تربط الحرفيين بالمشترين حول العالم، وتعزز العدالة، الثقة، والذكاء في التجارة الإبداعية.',
    'aboutUs': 'من نحن',
    'allRightsReserved': 'جميع الحقوق محفوظة.',
    'videos': 'الفيديوهات',
    'community': 'المجتمع',
    'discover': 'استكشف',
    'aboutPandaChao': 'عن Panda Chao',
    'whySell': 'لماذا البيع معنا؟',
    'creatorStories': 'قصص المبدعين',
    'faq': 'الأسئلة الشائعة',
    'communityServices': 'المجتمع والخدمات',
    'servicesMarketplace': 'سوق الخدمات',
    'becomeServiceProvider': 'انضم كمقدم خدمة',
    'blog': 'المدونة',
    'contact': 'تواصل معنا',
    'toolsLanguages': 'الأدوات واللغات',
    'languageSwitcher': 'اختر اللغة',
    'currencySwitcher': 'العملة',
    'appComingSoon': 'أيقونات المتاجر قادمة قريباً',
    'rightsReserved': '© باندتشاو 2025. جميع الحقوق محفوظة.',
    'terms': 'الشروط والأحكام',
    'privacy': 'سياسة الخصوصية',
    'homeHeroHeadline': 'باندتشاو — البيت العادل للحرفيين حول العالم',
    'homeHeroDescription': 'منصة اجتماعية-تجارية تربط الحرفيين المستقلين من الصين والعالم العربي والعالم، بالمشترين الباحثين عن منتجات يدوية أصيلة، في بيئة آمنة وعادلة مدعّمة بالذكاء الاصطناعي.',
    'homeHeroTitle': 'باندتشاو — البيت العادل للحرفيين حول العالم',
    'homeHeroCTA': 'تصفّح المنتجات',
    'featuredMakers': 'حرفيون مميزون',
    'featuredProducts': 'منتجات مميزة',
    'featuredVideos': 'فيديوهات مميزة',
    'viewAll': 'عرض الكل',
    'viewAllMakers': 'عرض جميع الحرفيين',
    'founderSectionTitle': 'مركز القيادة للمؤسس',
    'founderSectionDescription': 'للمؤسس: 6 مساعدين ذكاء اصطناعي متخصصين يساعدونك في القرارات الاستراتيجية، التقنية، الأمان، التجارة، المحتوى، واللوجستيات',
    'goToFounderConsole': 'اذهب إلى مركز المؤسس',
    'previous': 'السابق',
    'next': 'التالي',
    'allCategories': 'الكل',
    'decreaseQuantity': 'تقليل الكمية',
    'increaseQuantity': 'زيادة الكمية',
    'makerSince': 'حرفي منذ',
    'makerUnfollowButton': 'إلغاء المتابعة',
    'noStoryYet': 'لم يقم الحرفي بإضافة قصة بعد.',
    'noProductsYet': 'لا توجد منتجات مضافة بعد',
    'noVideosYet': 'لا توجد فيديوهات مضافة بعد',
    'viewAllProducts': 'عرض كل منتجات الحرفي',
    'viewAllVideos': 'عرض كل فيديوهات الحرفي',
    'founderCommandCenter': 'مركز القيادة للمؤسس',
    'founderHeroDescription': 'في Banda Chao، لديك 6 مساعدين ذكاء اصطناعي متخصصين يساعدونك في：',
    'founderAssistantsList': 'القرارات الاستراتيجية، التقنية، الأمان، التجارة، المحتوى، واللوجستيات',
    'totalUsers': 'إجمالي المستخدمين',
    'totalMakers': 'إجمالي الحرفيين',
    'goToAssistantsCenter': 'اذهب إلى مركز المساعدين',
    'founderOnlyAccess': 'الوصول مقصور على دور FOUNDER فقط',
    'yourSixAssistants': 'مساعدوك الستة',
    'eachAssistantSpecialized': 'كل مساعد متخصص في مجاله ويساعدك في اتخاذ قرارات أفضل',
    'quickLinks': 'روابط سريعة',
    'gettingStartedTitle': 'مرحباً بك في Banda Chao!',
    'gettingStartedDescription': 'اكتشف كيف يمكنك الاستفادة من المنصة: تصفح الحرفيين، استكشف المنتجات، شاهد الفيديوهات، واتبع المبدعين',
    'onboardingStep1Title': 'ما هو باندتشاو؟',
    'onboardingStep1Description': 'باندتشاو هو بيت اجتماعي-تجاري للحرفيين المستقلين، يربطهم بالمشترين المحبين للمنتجات اليدوية والأصيلة.',
    'onboardingStep2Title': 'عادل للحرفيين',
    'onboardingStep2Description': 'نضع الحرفيين أولاً عبر عمولات عادلة، أدوات بسيطة للتسعير الصحيح، ووصول مباشر لعملاء عالميين.',
    'onboardingStep3Title': 'آمن للمشترين',
    'onboardingStep3Description': 'اشترِ بثقة من حرفيين موثّقين، مع شحن واضح ومراجعات ودعم متى ما احتجت.',
    'onboardingStep4Title': 'مدعّم بذكاء الباندا',
    'onboardingStep4Description': 'مساعدون ودودون يعملون بالذكاء الاصطناعي لمساعدتك في التخطيط والترجمة وتطوير عملك بلغات متعددة.',
    'skip': 'تخطَّ',
    'watchVideos': 'شاهد الفيديوهات',
    'getStarted': 'ابدأ الآن',
    'close': 'إغلاق',
    'makersPage': 'صفحة الحرفيين',
    'exploreRegisteredMakers': 'استكشف الحرفيين المسجلين في المنصة',
    'contentAndVideos': 'المحتوى والفيديوهات',
    'browseVideosAndProducts': 'تصفح الفيديوهات والمنتجات المضافة',
    'reviewNotificationsAndControl': 'راجع الإشعارات ومركز التحكم',
    'exploreMakers': 'استكشف الحرفيين',
    'discoverTalentedMakers': 'اكتشف الحرفيين الموهوبين ومنتجاتهم الفريدة',
    'searchMakers': 'ابحث عن حرفي...',
    'loadingMakers': 'جاري تحميل الحرفيين...',
    'noMakersFound': 'لم يتم العثور على حرفيين',
    'tryDifferentSearch': 'جرب بحثاً مختلفاً أو قم بتغيير الفلاتر',
    'clearFilters': 'مسح الفلاتر',
    'showing': 'عرض',
    'of': 'من',
    'makers': 'حرفي',
    'location': 'الموقع',
    'allLocations': 'جميع المواقع',
    'noProductsInCategory': 'هذه الفئة لا تحتوي على منتجات بعد',
    'noProductsDescription': 'لا توجد منتجات متاحة حالياً',
    'noMakersDescription': 'لا يوجد حرفيون متاحون حالياً',
    'noVideosDescription': 'لا توجد فيديوهات متاحة حالياً',
    'unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'backToHome': 'العودة للصفحة الرئيسية',
    'myVideos': 'فيديوهاتي',
    'myProducts': 'منتجاتي',
    'uploadYourFirstVideo': 'ارفع أول فيديو لك',
    'addYourFirstProduct': 'أضف أول منتج لك',
    'priceTBD': 'السعر غير محدد',
    'views': 'مشاهدات',
    'uploadShortVideo': 'رفع فيديو قصير',
    'uploadLongVideo': 'رفع فيديو طويل',
    'shortVideoDescription': 'حد أقصى 60 ثانية لجذب انتباه المتابعين.',
    'longVideoDescription': 'حد أقصى 10 دقائق لعرض عملية التصنيع وقصة المنتج.',
    'minPrice': 'أقل سعر',
    'maxPrice': 'أعلى سعر',
    'to': 'إلى',
    'clearPriceFilter': 'مسح فلتر السعر',
    'noCategories': 'لا توجد فئات',
    'activeFilters': 'الفلاتر النشطة',
    'videoTitle': 'العنوان',
    'videoDescription': 'الوصف',
    'videoTitlePlaceholder': 'أدخل عنوان الفيديو',
    'videoDescriptionPlaceholder': 'اوصف فيديوك...',
    'videoFile': 'ملف الفيديو',
    'thumbnail': 'الصورة المصغرة',
    'selectVideoFile': 'انقر لاختيار ملف فيديو',
    'selectThumbnail': 'انقر لاختيار الصورة المصغرة',
    'videoType': 'نوع الفيديو',
    'maxDurationShort': 'حد أقصى 60 ثانية',
    'maxDurationLong': 'حد أقصى 10 دقائق',
    'duration': 'المدة',
    'selectVideoFileError': 'يرجى اختيار ملف فيديو',
    'selectImageFileError': 'يرجى اختيار ملف صورة',
    'pleaseLogin': 'يرجى تسجيل الدخول أولاً',
    'selectVideoAndThumbnail': 'يرجى اختيار الفيديو والصورة المصغرة',
    'enterVideoTitle': 'يرجى إدخال عنوان الفيديو',
    'cannotGetDuration': 'لا يمكن الحصول على مدة الفيديو',
    'shortVideoMaxDuration': 'لا يمكن أن يتجاوز الفيديو القصير 60 ثانية',
    'longVideoMaxDuration': 'لا يمكن أن يتجاوز الفيديو الطويل 10 دقائق',
    'uploadFailed': 'فشل الرفع',
    'uploading': 'جاري الرفع...',
    'cancel': 'إلغاء',
    'linkProducts': 'ربط المنتجات (اختياري)',
    'selectedProductsCount': 'تم اختيار {count} منتج',
    'loadingFilterOptions': 'جاري تحميل خيارات الفلترة...',
    'makerDashboard': 'لوحة تحكم الحرفي',
    'manageYourMakerProfile': 'إدارة ملفك الحرفي ومحتواك',
    'viewPublicProfile': 'عرض الملف العام',
    'editProfile': 'تعديل الملف',
    'editMakerProfile': 'تعديل ملف الحرفي',
    'notRegisteredAsMaker': 'لم تقم بإنشاء ملف حرفي بعد',
    'becomeMakerDescription': 'سجّل كحرفي لعرض منتجاتك ومحتواك على المنصة. شارك قصة حرفيتك مع العالم واجذب عملاء جدد.',
    'becomeMaker': 'ابدأ كحرفي',
    'createMakerProfile': 'إنشاء ملف حرفي',
    'makerOnboardingChecklist': 'قائمة متطلبات الحرفي',
    'makerOnboardingChecklistDesc': 'أكمل المتطلبات التالية لبدء البيع على المنصة',
    'makerRequirementProfile': 'إكمال معلومات الملف الشخصي',
    'makerRequirementProfileDesc': 'أضف اسمك ونبذة مختصرة عنك',
    'makerRequirementFirstProduct': 'إضافة أول منتج',
    'makerRequirementFirstProductDesc': 'أضف منتجك الأول ليظهر في متجرك',
    'makerRequirementFirstVideo': 'إضافة أول فيديو',
    'makerRequirementFirstVideoDesc': 'شارك فيديو يظهر مهاراتك أو منتجاتك',
    'makerRequirementProfilePicture': 'إضافة صورة شخصية',
    'makerRequirementProfilePictureDesc': 'أضف صورة شخصية لملفك',
    'makerRequirementStory': 'إضافة قصة الحرفي',
    'makerRequirementStoryDesc': 'شارك قصة حرفيتك (50 حرف على الأقل)',
    'makerReadyToGoLive': 'جاهز للانطلاق!',
    'makerReadyToGoLiveDesc': 'لقد أكملت جميع المتطلبات. متجرك جاهز للظهور للعملاء!',
    'makerAlmostReady': 'أنت تقريباً جاهز!',
    'makerAlmostReadyDesc': 'أكمل المتطلبات المتبقية لتحسين ملفك الشخصي',
    'makerNotReady': 'ليس جاهزاً بعد',
    'makerNotReadyDesc': 'أكمل على الأقل 3 متطلبات لبدء البيع',
    'completed': 'مكتمل',
    'progress': 'التقدم',
    'completeNow': 'أكمل الآن',
    'addPicture': 'إضافة صورة',
    'addStory': 'إضافة قصة',
    'nameRequired': 'الاسم مطلوب',
    'makerCreatedSuccess': 'تم إنشاء ملف الحرفي بنجاح！',
    'createMakerFailed': 'فشل في إنشاء ملف الحرفي',
    'makerUpdatedSuccess': 'تم تحديث ملف الحرفي بنجاح！',
    'updateMakerFailed': 'فشل في تحديث ملف الحرفي',
    'saving': 'جاري الحفظ...',
    'saveChanges': 'حفظ التعديلات',
    'creating': 'جاري الإنشاء...',
    'create': 'إنشاء',
    'totalVideos': 'إجمالي الفيديوهات',
    'totalProducts': 'إجمالي المنتجات',
    'totalViews': 'إجمالي المشاهدات',
    'totalLikes': 'إجمالي الإعجابات',
    'pillar1Title': 'عادل للحرفيين',
    'pillar1Body': 'عمولات شفافة، أدوات تسعير عادلة، ووصول مباشر لعملاء عالميين — ليحتفظ الحرفي بأكبر قيمة من كل عملية شراء.',
    'pillar2Title': 'آمن للمشترين',
    'pillar2Body': 'حرفيون موثّقون، شحن واضح، ونظام حماية للمشتري لبناء الثقة عبر الحدود.',
    'pillar3Title': 'مدعّم بذكاء الباندا',
    'pillar3Body': 'مساعدون أذكياء من عائلة الباندا يساعدون المؤسس والحرفي والمشتري في الترجمة، التخطيط، وتطوير العمل بثقة.',
    'featuredMakersTitle': 'صنّاع الأسبوع المميزون',
    'featuredMakerName1': 'ليلى تشين',
    'featuredMakerBio1': 'حرفية من جبال يونّان تستخدم أصباغاً نباتية لصنع شالات منسوجة يدوياً.',
    'featuredMakerName2': 'مريم وانغ',
    'featuredMakerBio2': 'تمزج بين الفخار التقليدي واللمسات العصرية لتقديم أطقم شاي دافئة.',
    'featuredMakerName3': 'هاو ليو',
    'featuredMakerBio3': 'حرفي في الجيل الرابع لفن الخيزران يصنع ديكوراً منزلياً مستداماً.',
    'latestProductsTitle': 'أحدث ما في مجتمعنا',
    'mockProductName1': 'طقم شاي حرفي',
    'mockProductDescription1': 'طقم شاي مصنوع يدوياً من الخزف المتين يناسب الجلسات اليومية.',
    'mockProductCategory1': 'الشاي',
    'mockProductName2': 'حقيبة توت منسوجة',
    'mockProductDescription2': 'حقيبة خفيفة ومتانة عالية تمنحك لمسة طبيعية.',
    'mockProductCategory2': 'إكسسوارات',
    'mockProductName3': 'مصباح خيزران هادئ',
    'mockProductDescription3': 'إضاءة ناعمة مع زخارف من الخيزران تزيد دفء المساحة.',
    'mockProductCategory3': 'ديكور منزلي',
    'mockProductName4': 'أكواب شاي مزخرفة',
    'mockProductDescription4': 'كل كوب يحمل رسماً فريداً باليد ليكون إضافة مميزة.',
    'mockProductCategory4': 'خزف',
    'howItWorksTitle': 'اكتشف. تواصل. ادعم.',
    'howItWorksStep1Title': '1. اكتشف القصص الأصيلة',
    'howItWorksStep1Description': 'تعرّف على رحلة كل صانع ومصدر إلهامه وراء كل منتج.',
    'howItWorksStep2Title': '2. تواصل مباشرة مع الصنّاع',
    'howItWorksStep2Description': 'ناقش الأفكار واطلب التصاميم الخاصة عبر منصتنا.',
    'howItWorksStep3Title': '3. ادعم الإبداع المستدام',
    'howItWorksStep3Description': 'بشرائك تساعد الصنّاع على الاستمرار في تقديم أعمال ذات قيمة.',
    'ctaHeadline': 'هل أنت صانع؟ انضم إلى مجتمعنا الآن.',
    'ctaButtonText': 'اعرف المزيد',
    'productsPageTitle': 'جميع المنتجات',
    'productsFilterCategoriesTitle': 'الفئات',
    'productsFilterCategoryApparel': 'الملابس',
    'productsFilterCategoryHomeDecor': 'ديكور المنزل',
    'productsFilterCategoryAccessories': 'الإكسسوارات',
    'productsFilterPriceTitle': 'نطاق السعر',
    'productsFilterPricePlaceholder': 'شريط السعر سيظهر هنا قريباً',
    'productsFilterMakersTitle': 'الصنّاع',
    'productsFilterMakerA': 'الصانع أ',
    'productsFilterMakerB': 'الصانع ب',
    'productsFilterMakerC': 'الصانع ج',
    'productDetailBy': 'بواسطة',
    'productDetailPlaceholderMaker': 'الحرفية ليلى',
    'productDetailPlaceholderTitle': 'مصباح خيزران منسوج يدويًا',
    'productDetailPlaceholderPrice': '329 درهم',
    'productDetailQuantity': 'الكمية',
    'productDetailAddToCart': 'أضف إلى السلة',
    'buyNow': 'اشتري الآن',
    'shipping': 'الشحن',
    'productDescription': 'تفاصيل المنتج',
    'similarProducts': 'منتجات مشابهة',
    'aboutThisMaker': 'حول هذا الحرفي',
    'moreFromThisMaker': 'المزيد من هذا الحرفي',
    'profile': 'الملف الشخصي',
    'productDetailStoryTitle': 'قصة المنتج',
    'productDetailStoryParagraph1': 'هذا المنتج من صنع الحرفية ليلى في جبال يونّان، حيث تمزج بين فن الخيزران التقليدي واللمسات المعاصرة لتقديم قطعة مميزة للمنزل.',
    'productDetailStoryParagraph2': 'تبدأ عملية التصنيع باختيار أعواد الخيزران بعناية، ثم تنظيفها وتجفيفها ومعالجتها بالبخار للحفاظ على متانتها وجمالها الطبيعي.',
    'productDetailStoryParagraph3': 'عند إضاءة المصباح تنعكس الظلال الناعمة على الجدران، ما يخلق أجواء دافئة وهادئة مثالية لغرفة المعيشة أو الزاوية المفضلة لديك.',
    'makerCoverAlt': 'صورة الغلاف لصانع المحتوى',
    'makerProfilePlaceholderName': 'تشانغ وي',
    'makerProfilePlaceholderBio': 'نجار من مقاطعة يونّان يصنع قصصًا دافئة من الخشب.',
    'makerFollowButton': 'متابعة',
    'makerStoryTitle': 'قصتي',
    'makerStoryParagraph1': 'ولدتُ في قرية صغيرة في يونّان وتعلمت النجارة على يد جدي. أرى عروق الخشب كشعر طبيعي يحمل حياةً خاصة بكل قطعة أصنعها.',
    'makerStoryParagraph2': 'أبحث دائمًا عن أفضل أنواع الخشب من مصادر مستدامة، وأعالج كل قطعة بعناية حتى أحافظ على ملمسها الدافئ وطابعها الأصلي.',
    'makerStoryParagraph3': 'أطمح أن تمنح منتجاتي إحساسًا بالسكينة لكل منزل، وأن أشجع المزيد من الشباب على الانضمام إلى عالم الحرف اليدوية.',
    'makerCreationsTitle': 'إبداعاتي',
    // Register page translations (Arabic - kept for future use)
    'registerTitle': 'إنشاء حساب جديد',
    'registerSubtitle': 'لديك حساب بالفعل؟',
    'registerLoginLink': 'تسجيل الدخول',
    'registerNameLabel': 'الاسم (اختياري)',
    'registerNamePlaceholder': 'اسمك',
    'registerEmailLabel': 'البريد الإلكتروني',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'كلمة المرور',
    'registerPasswordPlaceholder': '6 أحرف على الأقل',
    'registerConfirmPasswordLabel': 'تأكيد كلمة المرور',
    'registerConfirmPasswordPlaceholder': 'أعد إدخال كلمة المرور',
    'registerButton': 'إنشاء الحساب',
    'registerButtonLoading': 'جاري التسجيل...',
    'registerButtonSuccess': 'تم التسجيل!',
    'registerSuccessMessage': 'تم إنشاء الحساب بنجاح! جاري التوجيه...',
    'registerPasswordMismatch': 'كلمات المرور غير متطابقة',
    'registerPasswordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'registerEmailInvalid': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'registerNameTooShort': 'الاسم يجب أن يكون حرفين على الأقل',
    'registerError': 'فشل التسجيل، يرجى المحاولة مرة أخرى',
    'registerGoogleError': 'فشل في بدء التسجيل عبر Google',
    'registerOr': 'أو',
    'registerGoogleButton': 'التسجيل بواسطة Google',
    'assistants': 'المساعدون',
    'assistantsCenter': 'مركز المساعدين',
    'checkoutCartInvalid': 'بعض العناصر في سلة التسوق غير صالحة. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'checkoutPhoneInvalid': 'يرجى إدخال رقم هاتف صالح.',
    'checkoutErrorGeneric': 'تعذر إنشاء الطلب. يرجى المحاولة مرة أخرى.',
    'checkoutErrorValidation': 'بيانات الطلب غير صالحة. يرجى التحقق من سلة التسوق ومعلومات الشحن.',
    'checkoutErrorAuth': 'يرجى تسجيل الدخول لإكمال طلبك.',
    'checkoutErrorForbidden': 'ليس لديك صلاحية لإنشاء هذا الطلب.',
    'checkoutErrorConflict': 'يتعارض هذا الطلب مع بيانات موجودة. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'checkoutErrorServer': 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
    'checkoutFormInvalid': 'يرجى إكمال جميع حقول معلومات الشحن.',
    'processingPayment': 'جاري المعالجة...',
    'proceedToPayment': 'الانتقال إلى الدفع',
  },
  en: {
    'home': 'Home',
    'shortVideos': 'Short Videos',
    'longVideos': 'Long Videos',
    'products': 'Products',
    'search': 'Search',
    'chat': 'Chat',
    'feed': 'Feed',
    'uploadVideo': 'Upload Video',
    'addProduct': 'Add Product',
    'login': 'Log In',
    'register': 'Sign Up',
    'logout': 'Log Out',
    'myAccount': 'My Account',
    'loading': 'Loading...',
    'error': 'Error',
    'retry': 'Retry',
    'noContent': 'No content available',
    'viewMore': 'View more',
    'welcome': 'Welcome to Banda Chao',
    'subtitle': 'An innovative platform that blends social media and commerce',
    'subtitle2': 'Share stories, showcase products, connect globally',
    'watchShortVideos': 'Watch short videos',
    'browseProducts': 'Browse products',
    'hotShortVideos': 'Trending short videos',
    'featuredLongVideos': 'Featured long videos',
    'recommendedProducts': 'Recommended products',
    'language': 'Language',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'A neutral platform for makers to reach the world',
    'footerDescription': 'A social-commerce platform connecting makers and buyers worldwide, making creative trade fairer, safer, and more intelligent.',
    'about': 'About Banda Chao',
    'aboutDescription': 'A social-commerce platform connecting makers and buyers worldwide, making creative trade fairer, safer, and more intelligent.',
    'aboutUs': 'About us',
    'videos': 'Videos',
    'community': 'Community',
    'makers': 'Makers',
    'discover': 'Discover',
    'aboutPandaChao': 'About Banda Chao',
    'whySell': 'Why sell with us?',
    'creatorStories': 'Creator stories',
    'faq': 'FAQ',
    'communityServices': 'Community & Services',
    'servicesMarketplace': 'Services marketplace',
    'becomeServiceProvider': 'Become a service provider',
    'blog': 'Blog',
    'contact': 'Contact us',
    'toolsLanguages': 'Tools & Languages',
    'languageSwitcher': 'Switch language',
    'currencySwitcher': 'Currency',
    'appComingSoon': 'App store links coming soon',
    'rightsReserved': '© 2025 Banda Chao. All rights reserved.',
    'terms': 'Terms of use',
    'privacy': 'Privacy policy',
    'homeHeroHeadline': 'Banda Chao — The Fair Home for Makers Worldwide',
    'homeHeroDescription': 'A social-commerce platform that connects independent artisans from China, the Arab world, and across the globe with buyers who love original handmade goods — in a fair, safe, and AI-powered environment.',
    'homeHeroTitle': 'Banda Chao — The Fair Home for Makers Worldwide',
    'homeHeroCTA': 'Browse products',
    'watchVideos': 'Watch videos',
    'pillar1Title': 'Fair for creators',
    'pillar1Body': 'Transparent fees, fair pricing tools, and direct access to global buyers — so every sale feels truly worth it.',
    'pillar2Title': 'Trustworthy for buyers',
    'pillar2Body': 'Verified makers, clear shipping information, and buyer protection mechanisms that help build real trust across borders.',
    'pillar3Title': 'AI Pandas to help you grow',
    'pillar3Body': 'Built-in AI assistants — our "Pandas" — support founders, makers, and buyers with planning, translation, and business guidance.',
    'featuredMakers': 'Featured Makers',
    'featuredProducts': 'Featured Products',
    'featuredVideos': 'Featured Videos',
    'viewAll': 'View All',
    'viewAllMakers': 'View All Makers',
    'founderCommandCenter': 'Founder Command Center',
    'founderHeroDescription': 'At Banda Chao, you have 6 specialized AI assistants helping you with:',
    'founderAssistantsList': 'Strategic decisions, technology, security, commerce, content, and logistics',
    'totalUsers': 'Total Users',
    'totalMakers': 'Total Makers',
    'goToAssistantsCenter': 'Go to Assistants Center',
    'founderOnlyAccess': 'Access restricted to FOUNDER role only',
    'yourSixAssistants': 'Your Six Assistants',
    'eachAssistantSpecialized': 'Each assistant specializes in their field and helps you make better decisions',
    'quickLinks': 'Quick Links',
    'gettingStartedTitle': 'Welcome to Banda Chao!',
    'gettingStartedDescription': 'Discover how to make the most of the platform: browse makers, explore products, watch videos, and follow creators',
    'onboardingStep1Title': 'What is Banda Chao?',
    'onboardingStep1Description': 'Banda Chao is a social-commerce home for independent makers, helping buyers who love handmade goods discover pieces with real stories behind them.',
    'onboardingStep2Title': 'Fair to creators',
    'onboardingStep2Description': 'With transparent fees and simple pricing tools, makers can sell their work to the world at fair, sustainable prices.',
    'onboardingStep3Title': 'Peace of mind for buyers',
    'onboardingStep3Description': 'Authentic, verifiable maker profiles, clear shipping and logistics information, and essential buyer protection make cross-border shopping more confident and worry-free.',
    'onboardingStep4Title': 'AI Pandas by your side',
    'onboardingStep4Description': 'Friendly AI assistants — our "Banda Pandas" — offer multi-language translation, growth advice, and long-term support on your journey.',
    'skip': 'Skip',
    'getStarted': 'Get started',
    'close': 'Close',
    'makersPage': 'Makers Page',
    'exploreRegisteredMakers': 'Explore makers registered on the platform',
    'contentAndVideos': 'Content and Videos',
    'browseVideosAndProducts': 'Browse videos and products added',
    'reviewNotificationsAndControl': 'Review notifications and control center',
    'founderSectionTitle': 'Founder Command Center',
    'founderSectionDescription': 'For Founders: 6 specialized AI assistants help you with strategic decisions, technology, security, commerce, content, and logistics.',
    'goToFounderConsole': 'Go to Founder Console',
    'previous': 'Previous',
    'allCategories': 'All',
    'decreaseQuantity': 'Decrease quantity',
    'increaseQuantity': 'Increase quantity',
    'makerSince': 'Maker since',
    'makerUnfollowButton': 'Unfollow',
    'noStoryYet': 'No story added yet.',
    'noProductsYet': 'No products added yet',
    'noVideosYet': 'No videos added yet',
    'viewAllProducts': 'View all maker products',
    'viewAllVideos': 'View all maker videos',
    'exploreMakers': 'Explore Makers',
    'discoverTalentedMakers': 'Discover talented makers and their unique products',
    'searchMakers': 'Search for a maker...',
    'loadingMakers': 'Loading makers...',
    'noMakersFound': 'No makers found',
    'tryDifferentSearch': 'Try a different search or change filters',
    'clearFilters': 'Clear filters',
    'showing': 'Showing',
    'of': 'of',
    'location': 'Location',
    'allLocations': 'All locations',
    'noProductsInCategory': 'No products in this category yet',
    'noProductsDescription': 'No products available at the moment',
    'noMakersDescription': 'No makers available at the moment',
    'noVideosDescription': 'No videos available at the moment',
    'unexpectedError': 'An unexpected error occurred. Please try again.',
    'backToHome': 'Back to Home',
    'myVideos': 'My Videos',
    'myProducts': 'My Products',
    'uploadYourFirstVideo': 'Upload your first video',
    'addYourFirstProduct': 'Add your first product',
    'priceTBD': 'Price TBD',
    'views': 'views',
    'uploadShortVideo': 'Upload short video',
    'uploadLongVideo': 'Upload long video',
    'shortVideoDescription': 'Up to 60 seconds — perfect for grabbing attention and highlighting what makes your work special.',
    'longVideoDescription': 'Up to 10 minutes — ideal for showing your making process and sharing the full story.',
    'minPrice': 'Min price',
    'maxPrice': 'Max price',
    'to': 'to',
    'clearPriceFilter': 'Clear price filter',
    'noCategories': 'No categories',
    'activeFilters': 'Active filters',
    'videoTitle': 'Title',
    'videoDescription': 'Description',
    'videoTitlePlaceholder': 'Enter video title',
    'videoDescriptionPlaceholder': 'Describe your video...',
    'videoFile': 'Video file',
    'thumbnail': 'Thumbnail',
    'selectVideoFile': 'Click to select video file',
    'selectThumbnail': 'Click to select thumbnail',
    'videoType': 'Video type',
    'maxDurationShort': 'Up to 60 seconds',
    'maxDurationLong': 'Up to 10 minutes',
    'duration': 'Duration',
    'selectVideoFileError': 'Please select a video file',
    'selectImageFileError': 'Please select an image file',
    'pleaseLogin': 'Please log in first',
    'selectVideoAndThumbnail': 'Please select video and thumbnail',
    'enterVideoTitle': 'Please enter video title',
    'cannotGetDuration': 'Cannot get video duration',
    'shortVideoMaxDuration': 'Short video cannot exceed 60 seconds',
    'longVideoMaxDuration': 'Long video cannot exceed 10 minutes',
    'uploadFailed': 'Upload failed',
    'uploading': 'Uploading...',
    'cancel': 'Cancel',
    'linkProducts': 'Link Products (Optional)',
    'selectedProductsCount': '{count} products selected',
    'loadingFilterOptions': 'Loading filter options...',
    'makerDashboard': 'Maker dashboard',
    'manageYourMakerProfile': 'Manage your maker profile and content.',
    'viewPublicProfile': 'View Public Profile',
    'editProfile': 'Edit Profile',
    'editMakerProfile': 'Edit Maker Profile',
    'notRegisteredAsMaker': "You haven't created a maker profile yet",
    'becomeMakerDescription': 'Create your maker profile to showcase your story and connect with buyers from all around the world.',
    'becomeMaker': 'Become a maker',
    'createMakerProfile': 'Create Maker Profile',
    'makerOnboardingChecklist': 'Maker Onboarding Checklist',
    'makerOnboardingChecklistDesc': 'Complete the following requirements to start selling on the platform',
    'makerRequirementProfile': 'Complete profile information',
    'makerRequirementProfileDesc': 'Add your name and a brief bio',
    'makerRequirementFirstProduct': 'Add first product',
    'makerRequirementFirstProductDesc': 'Add your first product to display in your store',
    'makerRequirementFirstVideo': 'Add first video',
    'makerRequirementFirstVideoDesc': 'Share a video showcasing your skills or products',
    'makerRequirementProfilePicture': 'Add profile picture',
    'makerRequirementProfilePictureDesc': 'Add a picture to your profile',
    'makerRequirementStory': 'Add maker story',
    'makerRequirementStoryDesc': 'Share your craft story (at least 50 characters)',
    'makerReadyToGoLive': 'Ready to Go Live!',
    'makerReadyToGoLiveDesc': 'You have completed all requirements. Your store is ready to be shown to customers!',
    'makerAlmostReady': 'You are almost ready!',
    'makerAlmostReadyDesc': 'Complete the remaining requirements to improve your profile',
    'makerNotReady': 'Not Ready Yet',
    'makerNotReadyDesc': 'Complete at least 3 requirements to start selling',
    'completed': 'Completed',
    'progress': 'Progress',
    'completeNow': 'Complete Now',
    'addPicture': 'Add Picture',
    'addStory': 'Add Story',
    'nameRequired': 'Name is required',
    'makerCreatedSuccess': 'Maker profile created successfully!',
    'createMakerFailed': 'Failed to create maker profile',
    'makerUpdatedSuccess': 'Maker profile updated successfully!',
    'updateMakerFailed': 'Failed to update maker profile',
    'saving': 'Saving...',
    'saveChanges': 'Save Changes',
    'creating': 'Creating...',
    'create': 'Create',
    'totalVideos': 'Total videos',
    'totalProducts': 'Total products',
    'totalViews': 'Total views',
    'totalLikes': 'Total likes',
    'featuredMakersTitle': 'Featured Makers of the Week',
    'featuredMakerName1': 'Lina Chen',
    'featuredMakerBio1': 'A textile artist from Yunnan using natural dyes to weave cozy shawls.',
    'featuredMakerName2': 'Maya Wang',
    'featuredMakerBio2': 'Blending traditional ceramics with modern forms to craft warm tea sets.',
    'featuredMakerName3': 'Hao Liu',
    'featuredMakerBio3': 'A fourth-generation bamboo artisan creating sustainable home décor.',
    'latestProductsTitle': 'Latest from Our Community',
    'mockProductName1': 'Artisan Tea Set',
    'mockProductDescription1': 'Hand-thrown ceramic tea set perfect for daily rituals.',
    'mockProductCategory1': 'Tea',
    'mockProductName2': 'Handwoven Tote',
    'mockProductDescription2': 'Lightweight and sturdy tote that carries a touch of nature.',
    'mockProductCategory2': 'Accessories',
    'mockProductName3': 'Bamboo Night Lamp',
    'mockProductDescription3': 'Soft ambient light and bamboo patterns for a calming corner.',
    'mockProductCategory3': 'Home',
    'mockProductName4': 'Hand-Painted Tea Cups',
    'mockProductDescription4': 'Each cup features a unique hand-painted motif for collectors.',
    'mockProductCategory4': 'Ceramics',
    'howItWorksTitle': 'Discover. Connect. Support.',
    'howItWorksStep1Title': '1. Discover authentic stories',
    'howItWorksStep1Description': 'Learn the journey behind every product and the maker who created it.',
    'howItWorksStep2Title': '2. Connect directly with makers',
    'howItWorksStep2Description': 'Chat about custom requests or collaborations inside the platform.',
    'howItWorksStep3Title': '3. Support sustainable creativity',
    'howItWorksStep3Description': 'Your purchase keeps independent makers crafting meaningful goods.',
    'ctaHeadline': 'Are you a maker? Join our community.',
    'ctaButtonText': 'Learn More',
    'productsPageTitle': 'All Products',
    'productsFilterCategoriesTitle': 'Categories',
    'productsFilterCategoryApparel': 'Apparel',
    'productsFilterCategoryHomeDecor': 'Home Decor',
    'productsFilterCategoryAccessories': 'Accessories',
    'productsFilterPriceTitle': 'Price Range',
    'productsFilterPricePlaceholder': 'Price slider coming soon',
    'productsFilterMakersTitle': 'Makers',
    'productsFilterMakerA': 'Maker A',
    'productsFilterMakerB': 'Maker B',
    'productsFilterMakerC': 'Maker C',
    'productDetailBy': 'By',
    'productDetailPlaceholderMaker': 'Maker Lina',
    'productDetailPlaceholderTitle': 'Handwoven Bamboo Lamp',
    'productDetailPlaceholderPrice': '$129',
    'productDetailQuantity': 'Quantity',
    'productDetailAddToCart': 'Add to Cart',
    'buyNow': 'Buy Now',
    'shipping': 'Shipping',
    'productDescription': 'Product Details',
    'similarProducts': 'Similar Products',
    'aboutThisMaker': 'About this maker',
    'moreFromThisMaker': 'More from this maker',
    'profile': 'Profile',
    'productDetailStoryTitle': 'Product Story',
    'productDetailStoryParagraph1': 'Crafted by Lina in the Yunnan mountains, this piece blends traditional bamboo weaving with a modern silhouette to warm any room.',
    'productDetailStoryParagraph2': 'Each strand of bamboo is carefully selected, cleaned, and steamed to retain its flexibility and natural hue before being woven by hand.',
    'productDetailStoryParagraph3': 'When lit, the lamp casts gentle patterns that create a calming atmosphere — perfect for a living room corner or bedside table.',
    'makerCoverAlt': 'Maker cover photo',
    'makerProfilePlaceholderName': 'Zhang Wei',
    'makerProfilePlaceholderBio': 'Woodworker from Yunnan Province crafting stories in grain.',
    'makerFollowButton': 'Follow',
    'makerStoryTitle': 'My Story',
    'makerStoryParagraph1': 'I grew up in a small village in Yunnan, learning woodworking from my grandfather. Every grain of wood feels like poetry from nature.',
    'makerStoryParagraph2': 'I source timber carefully, working with local communities to ensure sustainable origins. Each piece is hand-finished to preserve the warmth of wood.',
    'makerStoryParagraph3': 'My hope is to bring calm into modern homes and inspire more young makers to embrace the craft.',
    'makerCreationsTitle': 'My Creations',
    // Register page translations
    'registerTitle': 'Create New Account',
    'registerSubtitle': 'Already have an account?',
    'registerLoginLink': 'Log In',
    'registerNameLabel': 'Name (Optional)',
    'registerNamePlaceholder': 'Your name',
    'registerEmailLabel': 'Email',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'Password',
    'registerPasswordPlaceholder': 'At least 6 characters',
    'registerConfirmPasswordLabel': 'Confirm Password',
    'registerConfirmPasswordPlaceholder': 'Re-enter your password',
    'registerButton': 'Create Account',
    'registerButtonLoading': 'Signing up...',
    'registerButtonSuccess': 'Signed up!',
    'registerSuccessMessage': 'Account created successfully! Redirecting...',
    'registerPasswordMismatch': 'Passwords do not match',
    'registerPasswordTooShort': 'Password must be at least 6 characters',
    'registerError': 'Registration failed, please try again',
    'registerGoogleError': 'Failed to start Google signup',
    'registerOr': 'Or',
    'registerGoogleButton': 'Sign up with Google',
    'assistants': 'Assistants',
    'assistantsCenter': 'Assistants Center',
    'checkoutCartInvalid': 'Some items in your cart are invalid. Please refresh and try again.',
    'checkoutPhoneInvalid': 'Please enter a valid phone number.',
    'checkoutErrorGeneric': 'Unable to create order. Please try again.',
    'checkoutErrorValidation': 'Invalid order data. Please check your cart and shipping information.',
    'checkoutErrorAuth': 'Please log in to complete your order.',
    'checkoutErrorForbidden': 'You do not have permission to create this order.',
    'checkoutErrorConflict': 'This order conflicts with existing data. Please refresh and try again.',
    'checkoutErrorServer': 'Server error. Please try again later.',
    'checkoutFormInvalid': 'Please complete all shipping information fields.',
    'processingPayment': 'Processing...',
    'proceedToPayment': 'Proceed to Payment',
    'productId': 'Product ID',
    'founderConsole': 'Founder Console',
    'founderAccount': 'Founder Account',
    'founder': 'Founder',
    'feedComingSoon': 'Creator Feed (Coming Soon)',
    'feedComingSoonDescription': 'The global social feed for makers and buyers will be implemented here soon. This will be the heart of our social commerce platform.',
    'feedShortVideosDescription': 'Discover artisan stories and product showcases through engaging short-form content.',
    'feedSocialCommerceDescription': 'Shop directly from posts and support artisans from China, Arabia, and the West.',
    'feedGlobalCommunityDescription': 'Connect with makers and buyers across three cultures in a neutral, safe space.',
    'developmentInProgress': 'Development in progress...',
    'markAllAsRead': 'Mark all as read',
    'totalNotifications': 'Total notifications: {total}',
    'loadMore': 'Load more',
    'justNow': 'Just now',
    'minutesAgo': '{minutes} minutes ago',
    'hoursAgo': '{hours} hours ago',
    'daysAgo': '{days} days ago',
    'socialCommerce': 'Social Commerce',
    'globalCommunity': 'Global Community',
  },
};

export const LanguageProvider: React.FC<{ 
  children: React.ReactNode;
  initialLocale?: Language;
}> = ({ children, initialLocale }) => {
  // Initialize with initialLocale if provided, otherwise default to 'zh'
  // This is safe because useState only runs on client-side after hydration
  const [language, setLanguageState] = useState<Language>(initialLocale || 'zh');

  useEffect(() => {
    // Only run in browser (client-side)
    if (typeof window === 'undefined') {
      return;
    }

    try {
      // If initialLocale is provided, use it and save to localStorage
      if (initialLocale && (initialLocale === 'zh' || initialLocale === 'ar' || initialLocale === 'en')) {
        setLanguageState(initialLocale);
        localStorage.setItem('language', initialLocale);
        return;
      }
      
      // Otherwise, load language from localStorage
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'ar' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      // localStorage may not be available (private browsing, etc.)
      // Silently fail and use default language
      console.warn('Failed to access localStorage in LanguageProvider:', error);
    }
  }, [initialLocale]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Only save to localStorage in browser
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('language', lang);
      } catch (error) {
        // localStorage may not be available - ignore
        console.warn('Failed to save language to localStorage:', error);
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Default context value used during prerendering or when no provider is present
const defaultLanguageContext: LanguageContextType = {
  language: 'en',
  setLanguage: () => {
    // No-op function for default context
  },
  t: (key: string) => key,
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Fallback used during prerendering or when no provider is present
    return defaultLanguageContext;
  }
  return context;
};

