'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  zh: {
    'home': '首页',
    'shortVideos': '短视频',
    'longVideos': '长视频',
    'products': '商品',
    'search': '搜索',
    'chat': '聊天',
    'feed': '动态',
    'uploadVideo': '上传视频',
    'addProduct': '添加商品',
    'login': '登录',
    'register': '注册',
    'logout': '退出',
    'myAccount': '我的账户',
    'loading': '加载中...',
    'error': '错误',
    'retry': '重试',
    'noContent': '暂无内容',
    'viewMore': '查看更多',
    'welcome': '欢迎来到 Panda Chao',
    'subtitle': '结合社交媒体与电子商务的创新平台',
    'subtitle2': '分享视频，展示产品，连接世界',
    'watchShortVideos': '观看短视频',
    'browseProducts': '浏览商品',
    'hotShortVideos': '热门短视频',
    'featuredLongVideos': '精选长视频',
    'recommendedProducts': '推荐商品',
    'language': '语言',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': '为世界上的创作者打造的中立平台',
    'footerDescription': '一个连接全球手作人与买家的社交电商平台，让创意交易更公平、更安全、更智能。',
    'about': '关于 Banda Chao',
    'aboutDescription': '一个连接全球手作人与买家的社交电商平台，让创意交易更公平、更安全、更智能。',
    'aboutUs': '关于我们',
    'allRightsReserved': '保留所有权利。',
    'videos': '视频',
    'community': '社区',
    'makers': '手作人',
    'discover': '探索',
    'aboutPandaChao': '关于 Panda Chao',
    'whySell': '为什么选择我们？',
    'creatorStories': '创作者故事',
    'faq': '常见问题',
    'communityServices': '社区与服务',
    'servicesMarketplace': '服务市场',
    'becomeServiceProvider': '成为服务提供者',
    'blog': '博客',
    'contact': '联系我们',
    'toolsLanguages': '工具与语言',
    'languageSwitcher': '切换语言',
    'currencySwitcher': '货币',
    'appComingSoon': '应用商店图标即将上线',
    'rightsReserved': '© 2025 Banda Chao. 保留所有权利。',
    'terms': '使用条款',
    'privacy': '隐私政策',
    'homeHeroHeadline': 'Banda Chao —— 全球手作人的公平之家',
    'homeHeroDescription': '一款社交电商平台，将来自中国、阿拉伯世界及全球各地的独立手作人，与寻找原创手作好物的买家连接在一起，在公平、安全并由人工智能加持的环境中完成交易。',
    'homeHeroTitle': 'Banda Chao —— 全球手作人的公平之家',
    'homeHeroCTA': '浏览商品',
    'watchVideos': '观看视频',
    'featuredMakers': '本周精选匠人',
    'featuredProducts': '社区最新上架',
    'featuredVideos': '精选视频',
    'viewAll': '查看更多',
    'founderSectionTitle': '创始人控制中心',
    'founderSectionDescription': '为创始人：6个专业AI助手帮助您进行战略决策、技术、安全、商务、内容和物流。',
    'goToFounderConsole': '前往创始人控制台',
    'previous': '上一页',
    'allCategories': '全部',
    'decreaseQuantity': '减少数量',
    'increaseQuantity': '增加数量',
    'makerSince': '自',
    'makerUnfollowButton': '取消关注',
    'noStoryYet': '还没有故事',
    'noProductsYet': '还没有产品',
    'noVideosYet': '还没有视频',
    'viewAllProducts': '查看所有产品',
    'viewAllVideos': '查看所有视频',
    'exploreMakers': '探索制造商',
    'discoverTalentedMakers': '发现才华横溢的制造商及其独特产品',
    'searchMakers': '搜索制造商...',
    'loadingMakers': '加载制造商...',
    'noMakersFound': '未找到制造商',
    'tryDifferentSearch': '尝试不同的搜索或更改过滤器',
    'clearFilters': '清除过滤器',
    'showing': '显示',
    'of': '的',
    'location': '位置',
    'allLocations': '所有位置',
    'noProductsInCategory': '此分类暂无商品',
    'noProductsDescription': '目前没有可用的商品',
    'noMakersDescription': '目前没有可用的制造商',
    'noVideosDescription': '目前没有可用的视频',
    'unexpectedError': '发生意外错误。请重试。',
    'backToHome': '返回首页',
    'myVideos': '我的视频',
    'myProducts': '我的产品',
    'uploadYourFirstVideo': '上传你的第一个视频',
    'addYourFirstProduct': '添加你的第一个产品',
    'priceTBD': '价格待定',
    'views': '观看',
    'uploadShortVideo': '上传短视频',
    'uploadLongVideo': '上传长视频',
    'shortVideoDescription': '最长 60 秒，用于吸引关注和讲述亮点。',
    'longVideoDescription': '最长 10 分钟，用于展示制作过程和完整故事。',
    'makerDashboard': '手作人控制台',
    'manageYourMakerProfile': '管理你的手作人档案和内容。',
    'viewPublicProfile': '查看公开档案',
    'editProfile': '编辑档案',
    'editMakerProfile': '编辑制造商档案',
    'notRegisteredAsMaker': '你还没有创建手作人档案',
    'becomeMakerDescription': '创建手作人档案，在平台上展示你的作品故事，与来自世界各地的买家建立联系。',
    'becomeMaker': '成为手作人',
    'createMakerProfile': '创建制造商档案',
    'makerOnboardingChecklist': '制造商入门清单',
    'makerOnboardingChecklistDesc': '完成以下要求以开始在平台上销售',
    'makerRequirementProfile': '完成个人资料信息',
    'makerRequirementProfileDesc': '添加您的姓名和简短简介',
    'makerRequirementFirstProduct': '添加第一个产品',
    'makerRequirementFirstProductDesc': '添加您的第一个产品以显示在您的商店中',
    'makerRequirementFirstVideo': '添加第一个视频',
    'makerRequirementFirstVideoDesc': '分享一个展示您技能或产品的视频',
    'makerRequirementProfilePicture': '添加个人资料图片',
    'makerRequirementProfilePictureDesc': '为您的个人资料添加图片',
    'makerRequirementStory': '添加制造商故事',
    'makerRequirementStoryDesc': '分享您的工艺故事（至少50个字符）',
    'makerReadyToGoLive': '准备上线！',
    'makerReadyToGoLiveDesc': '您已完成所有要求。您的商店已准备好向客户展示！',
    'makerAlmostReady': '您几乎准备好了！',
    'makerAlmostReadyDesc': '完成剩余要求以改善您的个人资料',
    'makerNotReady': '尚未准备好',
    'makerNotReadyDesc': '至少完成3个要求以开始销售',
    'completed': '已完成',
    'progress': '进度',
    'completeNow': '立即完成',
    'addPicture': '添加图片',
    'addStory': '添加故事',
    'nameRequired': '名称是必需的',
    'makerCreatedSuccess': '制造商档案创建成功！',
    'createMakerFailed': '创建制造商档案失败',
    'makerUpdatedSuccess': '制造商档案更新成功！',
    'updateMakerFailed': '更新制造商档案失败',
    'saving': '保存中...',
    'saveChanges': '保存更改',
    'creating': '创建中...',
    'create': '创建',
    'totalVideos': '总视频数',
    'totalProducts': '总商品数',
    'totalViews': '总浏览量',
    'totalLikes': '总点赞数',
    'pillar1Title': '对创作者公平',
    'pillar1Body': '透明抽成、公平定价工具和直达全球买家的渠道，让每一笔成交都更有价值。',
    'pillar2Title': '让买家安心',
    'pillar2Body': '经过验证的手作人、清晰的物流信息和买家保护机制，帮助跨境建立真正的信任。',
    'pillar3Title': 'AI 熊猫助你成长',
    'pillar3Body': '内置的 AI 助手「熊猫」，为创始人、手作人和买家提供规划、翻译和经营建议。',
    'founderCommandCenter': '创始人控制中心',
    'founderHeroDescription': '在 Banda Chao，您拥有6个专业AI助手，帮助您处理：',
    'founderAssistantsList': '战略决策、技术、安全、商务、内容和物流',
    'totalUsers': '总用户数',
    'totalMakers': '总制造商数',
    'goToAssistantsCenter': '前往助手中心',
    'founderOnlyAccess': '仅限FOUNDER角色访问',
    'yourSixAssistants': '您的六个助手',
    'eachAssistantSpecialized': '每个助手都专注于自己的领域，帮助您做出更好的决策',
    'quickLinks': '快速链接',
    'gettingStartedTitle': '欢迎来到 Banda Chao!',
    'gettingStartedDescription': '探索如何充分利用平台：浏览制造商，探索产品，观看视频，关注创作者',
    'onboardingStep1Title': '什么是 Banda Chao？',
    'onboardingStep1Description': 'Banda Chao 是面向独立手作人的社交电商之家，让热爱手作的买家更容易找到真正有故事的作品。',
    'onboardingStep2Title': '对创作者公平',
    'onboardingStep2Description': '通过透明抽成和简单易用的定价工具，帮助手作人用合理的价格把作品卖到全世界。',
    'onboardingStep3Title': '让买家安心',
    'onboardingStep3Description': '真实可验证的手作人档案、清晰的运费与物流信息，以及必要的买家保障，让跨境购物更放心。',
    'onboardingStep4Title': 'AI 熊猫在你身边',
    'onboardingStep4Description': '友好的 AI 助手「Banda 熊猫」为你提供多语言翻译、运营建议和成长陪伴。',
    'skip': '跳过',
    'getStarted': '立即开始',
    'close': '关闭',
    'makersPage': '制造商页面',
    'exploreRegisteredMakers': '探索平台上注册的制造商',
    'contentAndVideos': '内容和视频',
    'browseVideosAndProducts': '浏览添加的视频和产品',
    'reviewNotificationsAndControl': '查看通知和控制中心',
    'featuredMakersTitle': '本周精选匠人',
    'featuredMakerName1': '陈素素',
    'featuredMakerBio1': '来自云南山区的手工艺人，以天然植物染织手工披肩。',
    'featuredMakerName2': '王小梅',
    'featuredMakerBio2': '将传统陶艺与现代审美结合，打造温润的日常茶具。',
    'featuredMakerName3': '刘海涛',
    'featuredMakerBio3': '竹编第四代传承人，创作可持续的生活家居。',
    'latestProductsTitle': '社区最新上架',
    'mockProductName1': '匠心茶具套装',
    'mockProductDescription1': '手工拉坯烧制的茶具，适合日常品茗与待客。',
    'mockProductCategory1': '茶具',
    'mockProductName2': '手织藤编托特包',
    'mockProductDescription2': '轻盈又结实的手工托特包，带来自然气息。',
    'mockProductCategory2': '配饰',
    'mockProductName3': '竹制静夜台灯',
    'mockProductDescription3': '柔和灯光配合竹编纹理，营造温暖空间。',
    'mockProductCategory3': '家居',
    'mockProductName4': '手绘陶瓷茶杯',
    'mockProductDescription4': '每只杯子都带有独特的手绘图案，适合收藏。',
    'mockProductCategory4': '陶瓷',
    'howItWorksTitle': '发现・连接・支持',
    'howItWorksStep1Title': '1. 发现真实故事',
    'howItWorksStep1Description': '浏览匠人的创作历程与灵感来源，了解每件作品的背景。',
    'howItWorksStep2Title': '2. 直接联系创作者',
    'howItWorksStep2Description': '通过平台与创作者交流，提出定制需求或合作想法。',
    'howItWorksStep3Title': '3. 支持可持续创作',
    'howItWorksStep3Description': '购买带着温度的作品，让匠人持续创作更多好物。',
    'ctaHeadline': '你也是匠人吗？加入我们的社区。',
    'ctaButtonText': '了解更多',
    'productsPageTitle': '全部商品',
    'productsFilterCategoriesTitle': '分类',
    'productsFilterCategoryApparel': '服饰',
    'productsFilterCategoryHomeDecor': '家居装饰',
    'productsFilterCategoryAccessories': '配饰',
    'productsFilterPriceTitle': '价格区间',
    'productsFilterPricePlaceholder': '价格滑块即将上线',
    'productsFilterMakersTitle': '匠人',
    'productsFilterMakerA': '匠人 A',
    'productsFilterMakerB': '匠人 B',
    'productsFilterMakerC': '匠人 C',
    'productDetailBy': '来自',
    'productDetailPlaceholderMaker': '手工匠人 李娜',
    'productDetailPlaceholderTitle': '手工编织竹制灯具',
    'productDetailPlaceholderPrice': '¥329',
    'productDetailQuantity': '数量',
    'productDetailAddToCart': '加入购物车',
    'productDetailStoryTitle': '作品故事',
    'productDetailStoryParagraph1': '这件作品来自云南山区的匠人李娜，融合传统竹编技艺与现代生活美学。每一道纹理都由手工完成，保持竹材的自然韵味。',
    'productDetailStoryParagraph2': '制作过程中，匠人会精心挑选竹材，进行清洗、晾晒和蒸汽定型，确保灯具在使用时稳定耐用，同时保留竹材的原色。',
    'productDetailStoryParagraph3': '灯光透过竹编的纹理，在夜晚为空间带来温暖而宁静的光影，适合放置在卧室、书房或客厅角落，营造舒缓氛围。',
    'makerCoverAlt': '匠人主页封面图',
    'makerProfilePlaceholderName': '张伟',
    'makerProfilePlaceholderBio': '来自云南的木工匠人，用温暖木纹讲述家的故事。',
    'makerFollowButton': '关注',
    'makerStoryTitle': '我的故事',
    'makerStoryParagraph1': '我出生在云南的一个小山村，从小跟随外公学习木工。木头的纹理就像自然写下的诗，每一件作品都有独特的生命力。',
    'makerStoryParagraph2': '为了寻找最适合的木材，我常常深入山林，与当地村民交流，确保每块木头都来自可持续来源。制作过程中，我坚持手工打磨，只为保留木头的温润触感。',
    'makerStoryParagraph3': '我希望通过这些作品，让更多人感受到慢生活的温度，也希望支持更多年轻人加入到手工匠人的队伍中。',
    'makerCreationsTitle': '我的作品',
    // Register page translations
    'registerTitle': '创建新账户',
    'registerSubtitle': '已有账户？',
    'registerLoginLink': '登录',
    'registerNameLabel': '姓名（可选）',
    'registerNamePlaceholder': '您的姓名',
    'registerEmailLabel': '电子邮箱',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': '密码',
    'registerPasswordPlaceholder': '至少6个字符',
    'registerConfirmPasswordLabel': '确认密码',
    'registerConfirmPasswordPlaceholder': '请再次输入密码',
    'registerButton': '创建账户',
    'registerButtonLoading': '注册中...',
    'registerButtonSuccess': '注册成功！',
    'registerSuccessMessage': '账户创建成功！正在跳转...',
    'registerPasswordMismatch': '密码不匹配',
    'registerPasswordTooShort': '密码至少需要6个字符',
    'registerError': '注册失败，请重试',
    'registerGoogleError': 'Google注册失败',
    'registerOr': '或',
    'registerGoogleButton': '使用Google注册',
  },
  ar: {
    'home': 'الرئيسية',
    'shortVideos': 'فيديوهات قصيرة',
    'longVideos': 'فيديوهات طويلة',
    'products': 'المنتجات',
    'search': 'البحث',
    'chat': 'الدردشة',
    'feed': 'المنشورات',
    'uploadVideo': 'رفع فيديو',
    'addProduct': 'إضافة منتج',
    'login': 'تسجيل الدخول',
    'register': 'التسجيل',
    'logout': 'تسجيل الخروج',
    'myAccount': 'حسابي',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'retry': 'إعادة المحاولة',
    'noContent': 'لا يوجد محتوى',
    'viewMore': 'عرض المزيد',
    'welcome': 'مرحباً بك في Panda Chao',
    'subtitle': 'منصة مبتكرة تجمع بين التواصل الاجتماعي والتجارة الإلكترونية',
    'subtitle2': 'شارك الفيديوهات، اعرض المنتجات، واتصل بالعالم',
    'watchShortVideos': 'مشاهدة الفيديوهات القصيرة',
    'browseProducts': 'تصفح المنتجات',
    'hotShortVideos': 'الفيديوهات القصيرة الشائعة',
    'featuredLongVideos': 'الفيديوهات الطويلة المميزة',
    'recommendedProducts': 'المنتجات الموصى بها',
    'language': 'اللغة',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'منصة محايدة لدعم صنّاع المحتوى حول العالم',
    'footerDescription': 'منصة اجتماعية-تجارية تربط الحرفيين بالمشترين حول العالم، وتعزز العدالة، الثقة، والذكاء في التجارة الإبداعية.',
    'about': 'عن باندتشاو',
    'aboutDescription': 'منصة اجتماعية-تجارية تربط الحرفيين بالمشترين حول العالم، وتعزز العدالة، الثقة، والذكاء في التجارة الإبداعية.',
    'aboutUs': 'من نحن',
    'allRightsReserved': 'جميع الحقوق محفوظة.',
    'videos': 'الفيديوهات',
    'community': 'المجتمع',
    'discover': 'استكشف',
    'aboutPandaChao': 'عن Panda Chao',
    'whySell': 'لماذا البيع معنا؟',
    'creatorStories': 'قصص المبدعين',
    'faq': 'الأسئلة الشائعة',
    'communityServices': 'المجتمع والخدمات',
    'servicesMarketplace': 'سوق الخدمات',
    'becomeServiceProvider': 'انضم كمقدم خدمة',
    'blog': 'المدونة',
    'contact': 'تواصل معنا',
    'toolsLanguages': 'الأدوات واللغات',
    'languageSwitcher': 'اختر اللغة',
    'currencySwitcher': 'العملة',
    'appComingSoon': 'أيقونات المتاجر قادمة قريباً',
    'rightsReserved': '© باندتشاو 2025. جميع الحقوق محفوظة.',
    'terms': 'الشروط والأحكام',
    'privacy': 'سياسة الخصوصية',
    'homeHeroHeadline': 'باندتشاو — البيت العادل للحرفيين حول العالم',
    'homeHeroDescription': 'منصة اجتماعية-تجارية تربط الحرفيين المستقلين من الصين والعالم العربي والعالم، بالمشترين الباحثين عن منتجات يدوية أصيلة، في بيئة آمنة وعادلة مدعّمة بالذكاء الاصطناعي.',
    'homeHeroTitle': 'باندتشاو — البيت العادل للحرفيين حول العالم',
    'homeHeroCTA': 'تصفّح المنتجات',
    'featuredMakers': 'حرفيون مميزون',
    'featuredProducts': 'منتجات مميزة',
    'featuredVideos': 'فيديوهات مميزة',
    'viewAll': 'عرض الكل',
    'founderSectionTitle': 'مركز القيادة للمؤسس',
    'founderSectionDescription': 'للمؤسس: 6 مساعدين ذكاء اصطناعي متخصصين يساعدونك في القرارات الاستراتيجية، التقنية، الأمان، التجارة، المحتوى، واللوجستيات',
    'goToFounderConsole': 'اذهب إلى مركز المؤسس',
    'previous': 'السابق',
    'next': 'التالي',
    'allCategories': 'الكل',
    'decreaseQuantity': 'تقليل الكمية',
    'increaseQuantity': 'زيادة الكمية',
    'makerSince': 'حرفي منذ',
    'makerUnfollowButton': 'إلغاء المتابعة',
    'noStoryYet': 'لم يقم الحرفي بإضافة قصة بعد.',
    'noProductsYet': 'لا توجد منتجات مضافة بعد',
    'noVideosYet': 'لا توجد فيديوهات مضافة بعد',
    'viewAllProducts': 'عرض كل منتجات الحرفي',
    'viewAllVideos': 'عرض كل فيديوهات الحرفي',
    'founderCommandCenter': 'مركز القيادة للمؤسس',
    'founderHeroDescription': 'في Banda Chao، لديك 6 مساعدين ذكاء اصطناعي متخصصين يساعدونك في：',
    'founderAssistantsList': 'القرارات الاستراتيجية، التقنية، الأمان، التجارة، المحتوى، واللوجستيات',
    'totalUsers': 'إجمالي المستخدمين',
    'totalMakers': 'إجمالي الحرفيين',
    'goToAssistantsCenter': 'اذهب إلى مركز المساعدين',
    'founderOnlyAccess': 'الوصول مقصور على دور FOUNDER فقط',
    'yourSixAssistants': 'مساعدوك الستة',
    'eachAssistantSpecialized': 'كل مساعد متخصص في مجاله ويساعدك في اتخاذ قرارات أفضل',
    'quickLinks': 'روابط سريعة',
    'gettingStartedTitle': 'مرحباً بك في Banda Chao!',
    'gettingStartedDescription': 'اكتشف كيف يمكنك الاستفادة من المنصة: تصفح الحرفيين، استكشف المنتجات، شاهد الفيديوهات، واتبع المبدعين',
    'onboardingStep1Title': 'ما هو باندتشاو؟',
    'onboardingStep1Description': 'باندتشاو هو بيت اجتماعي-تجاري للحرفيين المستقلين، يربطهم بالمشترين المحبين للمنتجات اليدوية والأصيلة.',
    'onboardingStep2Title': 'عادل للحرفيين',
    'onboardingStep2Description': 'نضع الحرفيين أولاً عبر عمولات عادلة، أدوات بسيطة للتسعير الصحيح، ووصول مباشر لعملاء عالميين.',
    'onboardingStep3Title': 'آمن للمشترين',
    'onboardingStep3Description': 'اشترِ بثقة من حرفيين موثّقين، مع شحن واضح ومراجعات ودعم متى ما احتجت.',
    'onboardingStep4Title': 'مدعّم بذكاء الباندا',
    'onboardingStep4Description': 'مساعدون ودودون يعملون بالذكاء الاصطناعي لمساعدتك في التخطيط والترجمة وتطوير عملك بلغات متعددة.',
    'skip': 'تخطَّ',
    'watchVideos': 'شاهد الفيديوهات',
    'getStarted': 'ابدأ الآن',
    'close': 'إغلاق',
    'makersPage': 'صفحة الحرفيين',
    'exploreRegisteredMakers': 'استكشف الحرفيين المسجلين في المنصة',
    'contentAndVideos': 'المحتوى والفيديوهات',
    'browseVideosAndProducts': 'تصفح الفيديوهات والمنتجات المضافة',
    'reviewNotificationsAndControl': 'راجع الإشعارات ومركز التحكم',
    'exploreMakers': 'استكشف الحرفيين',
    'discoverTalentedMakers': 'اكتشف الحرفيين الموهوبين ومنتجاتهم الفريدة',
    'searchMakers': 'ابحث عن حرفي...',
    'loadingMakers': 'جاري تحميل الحرفيين...',
    'noMakersFound': 'لم يتم العثور على حرفيين',
    'tryDifferentSearch': 'جرب بحثاً مختلفاً أو قم بتغيير الفلاتر',
    'clearFilters': 'مسح الفلاتر',
    'showing': 'عرض',
    'of': 'من',
    'makers': 'حرفي',
    'location': 'الموقع',
    'allLocations': 'جميع المواقع',
    'noProductsInCategory': 'هذه الفئة لا تحتوي على منتجات بعد',
    'noProductsDescription': 'لا توجد منتجات متاحة حالياً',
    'noMakersDescription': 'لا يوجد حرفيون متاحون حالياً',
    'noVideosDescription': 'لا توجد فيديوهات متاحة حالياً',
    'unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'backToHome': 'العودة للصفحة الرئيسية',
    'myVideos': 'فيديوهاتي',
    'myProducts': 'منتجاتي',
    'uploadYourFirstVideo': 'ارفع أول فيديو لك',
    'addYourFirstProduct': 'أضف أول منتج لك',
    'priceTBD': 'السعر غير محدد',
    'views': 'مشاهدات',
    'uploadShortVideo': 'رفع فيديو قصير',
    'uploadLongVideo': 'رفع فيديو طويل',
    'shortVideoDescription': 'حد أقصى 60 ثانية لجذب انتباه المتابعين.',
    'longVideoDescription': 'حد أقصى 10 دقائق لعرض عملية التصنيع وقصة المنتج.',
    'makerDashboard': 'لوحة تحكم الحرفي',
    'manageYourMakerProfile': 'إدارة ملفك الحرفي ومحتواك',
    'viewPublicProfile': 'عرض الملف العام',
    'editProfile': 'تعديل الملف',
    'editMakerProfile': 'تعديل ملف الحرفي',
    'notRegisteredAsMaker': 'لم تقم بإنشاء ملف حرفي بعد',
    'becomeMakerDescription': 'سجّل كحرفي لعرض منتجاتك ومحتواك على المنصة. شارك قصة حرفيتك مع العالم واجذب عملاء جدد.',
    'becomeMaker': 'ابدأ كحرفي',
    'createMakerProfile': 'إنشاء ملف حرفي',
    'makerOnboardingChecklist': 'قائمة متطلبات الحرفي',
    'makerOnboardingChecklistDesc': 'أكمل المتطلبات التالية لبدء البيع على المنصة',
    'makerRequirementProfile': 'إكمال معلومات الملف الشخصي',
    'makerRequirementProfileDesc': 'أضف اسمك ونبذة مختصرة عنك',
    'makerRequirementFirstProduct': 'إضافة أول منتج',
    'makerRequirementFirstProductDesc': 'أضف منتجك الأول ليظهر في متجرك',
    'makerRequirementFirstVideo': 'إضافة أول فيديو',
    'makerRequirementFirstVideoDesc': 'شارك فيديو يظهر مهاراتك أو منتجاتك',
    'makerRequirementProfilePicture': 'إضافة صورة شخصية',
    'makerRequirementProfilePictureDesc': 'أضف صورة شخصية لملفك',
    'makerRequirementStory': 'إضافة قصة الحرفي',
    'makerRequirementStoryDesc': 'شارك قصة حرفيتك (50 حرف على الأقل)',
    'makerReadyToGoLive': 'جاهز للانطلاق!',
    'makerReadyToGoLiveDesc': 'لقد أكملت جميع المتطلبات. متجرك جاهز للظهور للعملاء!',
    'makerAlmostReady': 'أنت تقريباً جاهز!',
    'makerAlmostReadyDesc': 'أكمل المتطلبات المتبقية لتحسين ملفك الشخصي',
    'makerNotReady': 'ليس جاهزاً بعد',
    'makerNotReadyDesc': 'أكمل على الأقل 3 متطلبات لبدء البيع',
    'completed': 'مكتمل',
    'progress': 'التقدم',
    'completeNow': 'أكمل الآن',
    'addPicture': 'إضافة صورة',
    'addStory': 'إضافة قصة',
    'nameRequired': 'الاسم مطلوب',
    'makerCreatedSuccess': 'تم إنشاء ملف الحرفي بنجاح！',
    'createMakerFailed': 'فشل في إنشاء ملف الحرفي',
    'makerUpdatedSuccess': 'تم تحديث ملف الحرفي بنجاح！',
    'updateMakerFailed': 'فشل في تحديث ملف الحرفي',
    'saving': 'جاري الحفظ...',
    'saveChanges': 'حفظ التعديلات',
    'creating': 'جاري الإنشاء...',
    'create': 'إنشاء',
    'totalVideos': 'إجمالي الفيديوهات',
    'totalProducts': 'إجمالي المنتجات',
    'totalViews': 'إجمالي المشاهدات',
    'totalLikes': 'إجمالي الإعجابات',
    'pillar1Title': 'عادل للحرفيين',
    'pillar1Body': 'عمولات شفافة، أدوات تسعير عادلة، ووصول مباشر لعملاء عالميين — ليحتفظ الحرفي بأكبر قيمة من كل عملية شراء.',
    'pillar2Title': 'آمن للمشترين',
    'pillar2Body': 'حرفيون موثّقون، شحن واضح، ونظام حماية للمشتري لبناء الثقة عبر الحدود.',
    'pillar3Title': 'مدعّم بذكاء الباندا',
    'pillar3Body': 'مساعدون أذكياء من عائلة الباندا يساعدون المؤسس والحرفي والمشتري في الترجمة، التخطيط، وتطوير العمل بثقة.',
    'featuredMakersTitle': 'صنّاع الأسبوع المميزون',
    'featuredMakerName1': 'ليلى تشين',
    'featuredMakerBio1': 'حرفية من جبال يونّان تستخدم أصباغاً نباتية لصنع شالات منسوجة يدوياً.',
    'featuredMakerName2': 'مريم وانغ',
    'featuredMakerBio2': 'تمزج بين الفخار التقليدي واللمسات العصرية لتقديم أطقم شاي دافئة.',
    'featuredMakerName3': 'هاو ليو',
    'featuredMakerBio3': 'حرفي في الجيل الرابع لفن الخيزران يصنع ديكوراً منزلياً مستداماً.',
    'latestProductsTitle': 'أحدث ما في مجتمعنا',
    'mockProductName1': 'طقم شاي حرفي',
    'mockProductDescription1': 'طقم شاي مصنوع يدوياً من الخزف المتين يناسب الجلسات اليومية.',
    'mockProductCategory1': 'الشاي',
    'mockProductName2': 'حقيبة توت منسوجة',
    'mockProductDescription2': 'حقيبة خفيفة ومتانة عالية تمنحك لمسة طبيعية.',
    'mockProductCategory2': 'إكسسوارات',
    'mockProductName3': 'مصباح خيزران هادئ',
    'mockProductDescription3': 'إضاءة ناعمة مع زخارف من الخيزران تزيد دفء المساحة.',
    'mockProductCategory3': 'ديكور منزلي',
    'mockProductName4': 'أكواب شاي مزخرفة',
    'mockProductDescription4': 'كل كوب يحمل رسماً فريداً باليد ليكون إضافة مميزة.',
    'mockProductCategory4': 'خزف',
    'howItWorksTitle': 'اكتشف. تواصل. ادعم.',
    'howItWorksStep1Title': '1. اكتشف القصص الأصيلة',
    'howItWorksStep1Description': 'تعرّف على رحلة كل صانع ومصدر إلهامه وراء كل منتج.',
    'howItWorksStep2Title': '2. تواصل مباشرة مع الصنّاع',
    'howItWorksStep2Description': 'ناقش الأفكار واطلب التصاميم الخاصة عبر منصتنا.',
    'howItWorksStep3Title': '3. ادعم الإبداع المستدام',
    'howItWorksStep3Description': 'بشرائك تساعد الصنّاع على الاستمرار في تقديم أعمال ذات قيمة.',
    'ctaHeadline': 'هل أنت صانع؟ انضم إلى مجتمعنا الآن.',
    'ctaButtonText': 'اعرف المزيد',
    'productsPageTitle': 'جميع المنتجات',
    'productsFilterCategoriesTitle': 'الفئات',
    'productsFilterCategoryApparel': 'الملابس',
    'productsFilterCategoryHomeDecor': 'ديكور المنزل',
    'productsFilterCategoryAccessories': 'الإكسسوارات',
    'productsFilterPriceTitle': 'نطاق السعر',
    'productsFilterPricePlaceholder': 'شريط السعر سيظهر هنا قريباً',
    'productsFilterMakersTitle': 'الصنّاع',
    'productsFilterMakerA': 'الصانع أ',
    'productsFilterMakerB': 'الصانع ب',
    'productsFilterMakerC': 'الصانع ج',
    'productDetailBy': 'بواسطة',
    'productDetailPlaceholderMaker': 'الحرفية ليلى',
    'productDetailPlaceholderTitle': 'مصباح خيزران منسوج يدويًا',
    'productDetailPlaceholderPrice': '329 درهم',
    'productDetailQuantity': 'الكمية',
    'productDetailAddToCart': 'أضف إلى السلة',
    'productDetailStoryTitle': 'قصة المنتج',
    'productDetailStoryParagraph1': 'هذا المنتج من صنع الحرفية ليلى في جبال يونّان، حيث تمزج بين فن الخيزران التقليدي واللمسات المعاصرة لتقديم قطعة مميزة للمنزل.',
    'productDetailStoryParagraph2': 'تبدأ عملية التصنيع باختيار أعواد الخيزران بعناية، ثم تنظيفها وتجفيفها ومعالجتها بالبخار للحفاظ على متانتها وجمالها الطبيعي.',
    'productDetailStoryParagraph3': 'عند إضاءة المصباح تنعكس الظلال الناعمة على الجدران، ما يخلق أجواء دافئة وهادئة مثالية لغرفة المعيشة أو الزاوية المفضلة لديك.',
    'makerCoverAlt': 'صورة الغلاف لصانع المحتوى',
    'makerProfilePlaceholderName': 'تشانغ وي',
    'makerProfilePlaceholderBio': 'نجار من مقاطعة يونّان يصنع قصصًا دافئة من الخشب.',
    'makerFollowButton': 'متابعة',
    'makerStoryTitle': 'قصتي',
    'makerStoryParagraph1': 'ولدتُ في قرية صغيرة في يونّان وتعلمت النجارة على يد جدي. أرى عروق الخشب كشعر طبيعي يحمل حياةً خاصة بكل قطعة أصنعها.',
    'makerStoryParagraph2': 'أبحث دائمًا عن أفضل أنواع الخشب من مصادر مستدامة، وأعالج كل قطعة بعناية حتى أحافظ على ملمسها الدافئ وطابعها الأصلي.',
    'makerStoryParagraph3': 'أطمح أن تمنح منتجاتي إحساسًا بالسكينة لكل منزل، وأن أشجع المزيد من الشباب على الانضمام إلى عالم الحرف اليدوية.',
    'makerCreationsTitle': 'إبداعاتي',
    // Register page translations (Arabic - kept for future use)
    'registerTitle': 'إنشاء حساب جديد',
    'registerSubtitle': 'لديك حساب بالفعل؟',
    'registerLoginLink': 'تسجيل الدخول',
    'registerNameLabel': 'الاسم (اختياري)',
    'registerNamePlaceholder': 'اسمك',
    'registerEmailLabel': 'البريد الإلكتروني',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'كلمة المرور',
    'registerPasswordPlaceholder': '6 أحرف على الأقل',
    'registerConfirmPasswordLabel': 'تأكيد كلمة المرور',
    'registerConfirmPasswordPlaceholder': 'أعد إدخال كلمة المرور',
    'registerButton': 'إنشاء الحساب',
    'registerButtonLoading': 'جاري التسجيل...',
    'registerButtonSuccess': 'تم التسجيل!',
    'registerSuccessMessage': 'تم إنشاء الحساب بنجاح! جاري التوجيه...',
    'registerPasswordMismatch': 'كلمات المرور غير متطابقة',
    'registerPasswordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'registerError': 'فشل التسجيل، يرجى المحاولة مرة أخرى',
    'registerGoogleError': 'فشل في بدء التسجيل عبر Google',
    'registerOr': 'أو',
    'registerGoogleButton': 'التسجيل بواسطة Google',
    'assistants': 'المساعدون',
    'assistantsCenter': 'مركز المساعدين',
    'checkoutCartInvalid': 'بعض العناصر في سلة التسوق غير صالحة. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'checkoutPhoneInvalid': 'يرجى إدخال رقم هاتف صالح.',
    'checkoutErrorGeneric': 'تعذر إنشاء الطلب. يرجى المحاولة مرة أخرى.',
    'checkoutErrorValidation': 'بيانات الطلب غير صالحة. يرجى التحقق من سلة التسوق ومعلومات الشحن.',
    'checkoutErrorAuth': 'يرجى تسجيل الدخول لإكمال طلبك.',
    'checkoutErrorForbidden': 'ليس لديك صلاحية لإنشاء هذا الطلب.',
    'checkoutErrorConflict': 'يتعارض هذا الطلب مع بيانات موجودة. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'checkoutErrorServer': 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
  },
  en: {
    'home': 'Home',
    'shortVideos': 'Short Videos',
    'longVideos': 'Long Videos',
    'products': 'Products',
    'search': 'Search',
    'chat': 'Chat',
    'feed': 'Feed',
    'uploadVideo': 'Upload Video',
    'addProduct': 'Add Product',
    'login': 'Log In',
    'register': 'Sign Up',
    'logout': 'Log Out',
    'myAccount': 'My Account',
    'loading': 'Loading...',
    'error': 'Error',
    'retry': 'Retry',
    'noContent': 'No content available',
    'viewMore': 'View more',
    'welcome': 'Welcome to Panda Chao',
    'subtitle': 'An innovative platform that blends social media and commerce',
    'subtitle2': 'Share stories, showcase products, connect globally',
    'watchShortVideos': 'Watch short videos',
    'browseProducts': 'Browse products',
    'hotShortVideos': 'Trending short videos',
    'featuredLongVideos': 'Featured long videos',
    'recommendedProducts': 'Recommended products',
    'language': 'Language',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'A neutral platform for makers to reach the world',
    'discover': 'Discover',
    'aboutPandaChao': 'About Panda Chao',
    'whySell': 'Why sell with us?',
    'creatorStories': 'Creator stories',
    'faq': 'FAQ',
    'communityServices': 'Community & Services',
    'servicesMarketplace': 'Services marketplace',
    'becomeServiceProvider': 'Become a service provider',
    'blog': 'Blog',
    'contact': 'Contact us',
    'toolsLanguages': 'Tools & Languages',
    'languageSwitcher': 'Switch language',
    'currencySwitcher': 'Currency',
    'appComingSoon': 'App store links coming soon',
    'rightsReserved': '© 2025 Panda Chao. All rights reserved.',
    'terms': 'Terms of Service',
    'privacy': 'Privacy Policy',
    'homeHeroHeadline': 'Banda Chao — A Fair Home for Global Makers',
    'homeHeroDescription': 'A social-commerce platform that connects independent artisans from China, the Arab world, and beyond with buyers worldwide, in a fair, safe, and AI-powered marketplace.',
    'homeHeroTitle': 'Banda Chao — A Fair Home for Global Makers',
    'homeHeroCTA': 'Explore the marketplace',
    'pillar1Title': 'Fair for Makers',
    'pillar1Body': 'Transparent fees, fair pricing tools, and direct access to global buyers — so makers keep more from every sale.',
    'pillar2Title': 'Safe for Buyers',
    'pillar2Body': 'Verified makers, clear shipping, and buyer protection features to build real trust across borders.',
    'pillar3Title': 'Smart with AI Pandas',
    'pillar3Body': 'Built-in AI assistants ("Pandas") that help founders, makers, and buyers plan, translate, and grow with confidence.',
    'featuredMakers': 'Featured Makers',
    'featuredProducts': 'Featured Products',
    'featuredVideos': 'Featured Videos',
    'viewAll': 'View All',
    'founderCommandCenter': 'Founder Command Center',
    'founderHeroDescription': 'At Banda Chao, you have 6 specialized AI assistants helping you with:',
    'founderAssistantsList': 'Strategic decisions, technology, security, commerce, content, and logistics',
    'totalUsers': 'Total Users',
    'totalMakers': 'Total Makers',
    'goToAssistantsCenter': 'Go to Assistants Center',
    'founderOnlyAccess': 'Access restricted to FOUNDER role only',
    'yourSixAssistants': 'Your Six Assistants',
    'eachAssistantSpecialized': 'Each assistant specializes in their field and helps you make better decisions',
    'quickLinks': 'Quick Links',
    'gettingStartedTitle': 'Welcome to Banda Chao!',
    'gettingStartedDescription': 'Discover how to make the most of the platform: browse makers, explore products, watch videos, and follow creators',
    'onboardingStep1Title': 'What is Banda Chao?',
    'onboardingStep1Description': 'Banda Chao is a social-commerce home for independent artisans, connecting makers with buyers who love handmade and artisanal products.',
    'onboardingStep2Title': 'Fair for Makers',
    'onboardingStep2Description': 'We put makers first with transparent fees, simple tools to set fair prices, and direct access to global customers.',
    'onboardingStep3Title': 'Safe for Buyers',
    'onboardingStep3Description': 'Buy with confidence from verified makers, with clear shipping, reviews, and support when you need it.',
    'onboardingStep4Title': 'Powered by AI Pandas',
    'onboardingStep4Description': 'Friendly AI assistants — the Banda Chao Pandas — help you plan, translate, and grow your business in multiple languages.',
    'skip': 'Skip',
    'getStarted': 'Get Started',
    'close': 'Close',
    'makersPage': 'Makers Page',
    'exploreRegisteredMakers': 'Explore makers registered on the platform',
    'contentAndVideos': 'Content and Videos',
    'browseVideosAndProducts': 'Browse videos and products added',
    'reviewNotificationsAndControl': 'Review notifications and control center',
    'founderSectionTitle': 'Founder Command Center',
    'founderSectionDescription': 'For Founders: 6 specialized AI assistants help you with strategic decisions, technology, security, commerce, content, and logistics.',
    'goToFounderConsole': 'Go to Founder Console',
    'previous': 'Previous',
    'allCategories': 'All',
    'decreaseQuantity': 'Decrease quantity',
    'increaseQuantity': 'Increase quantity',
    'makerSince': 'Maker since',
    'makerUnfollowButton': 'Unfollow',
    'noStoryYet': 'No story added yet.',
    'noProductsYet': 'No products added yet',
    'noVideosYet': 'No videos added yet',
    'viewAllProducts': 'View all maker products',
    'viewAllVideos': 'View all maker videos',
    'exploreMakers': 'Explore Makers',
    'discoverTalentedMakers': 'Discover talented makers and their unique products',
    'searchMakers': 'Search for a maker...',
    'loadingMakers': 'Loading makers...',
    'noMakersFound': 'No makers found',
    'tryDifferentSearch': 'Try a different search or change filters',
    'clearFilters': 'Clear filters',
    'showing': 'Showing',
    'of': 'of',
    'makers': 'makers',
    'location': 'Location',
    'allLocations': 'All locations',
    'noProductsInCategory': 'No products in this category yet',
    'noProductsDescription': 'No products available at the moment',
    'noMakersDescription': 'No makers available at the moment',
    'noVideosDescription': 'No videos available at the moment',
    'unexpectedError': 'An unexpected error occurred. Please try again.',
    'backToHome': 'Back to Home',
    'myVideos': 'My Videos',
    'myProducts': 'My Products',
    'uploadYourFirstVideo': 'Upload your first video',
    'addYourFirstProduct': 'Add your first product',
    'priceTBD': 'Price TBD',
    'views': 'views',
    'uploadShortVideo': 'Upload Short Video',
    'uploadLongVideo': 'Upload Long Video',
    'shortVideoDescription': 'Up to 60 seconds, for attention-grabbing content',
    'longVideoDescription': 'Up to 10 minutes, for documenting the making process',
    'makerDashboard': 'Maker Dashboard',
    'manageYourMakerProfile': 'Manage your maker profile and content',
    'viewPublicProfile': 'View Public Profile',
    'editProfile': 'Edit Profile',
    'editMakerProfile': 'Edit Maker Profile',
    'notRegisteredAsMaker': 'You have not registered as a maker yet',
    'becomeMakerDescription': 'Register as a maker to showcase your products and content on the platform. Share your craft story with the world and attract new customers.',
    'becomeMaker': 'Become a Maker',
    'createMakerProfile': 'Create Maker Profile',
    'makerOnboardingChecklist': 'Maker Onboarding Checklist',
    'makerOnboardingChecklistDesc': 'Complete the following requirements to start selling on the platform',
    'makerRequirementProfile': 'Complete profile information',
    'makerRequirementProfileDesc': 'Add your name and a brief bio',
    'makerRequirementFirstProduct': 'Add first product',
    'makerRequirementFirstProductDesc': 'Add your first product to display in your store',
    'makerRequirementFirstVideo': 'Add first video',
    'makerRequirementFirstVideoDesc': 'Share a video showcasing your skills or products',
    'makerRequirementProfilePicture': 'Add profile picture',
    'makerRequirementProfilePictureDesc': 'Add a picture to your profile',
    'makerRequirementStory': 'Add maker story',
    'makerRequirementStoryDesc': 'Share your craft story (at least 50 characters)',
    'makerReadyToGoLive': 'Ready to Go Live!',
    'makerReadyToGoLiveDesc': 'You have completed all requirements. Your store is ready to be shown to customers!',
    'makerAlmostReady': 'You are almost ready!',
    'makerAlmostReadyDesc': 'Complete the remaining requirements to improve your profile',
    'makerNotReady': 'Not Ready Yet',
    'makerNotReadyDesc': 'Complete at least 3 requirements to start selling',
    'completed': 'Completed',
    'progress': 'Progress',
    'completeNow': 'Complete Now',
    'addPicture': 'Add Picture',
    'addStory': 'Add Story',
    'nameRequired': 'Name is required',
    'makerCreatedSuccess': 'Maker profile created successfully!',
    'createMakerFailed': 'Failed to create maker profile',
    'makerUpdatedSuccess': 'Maker profile updated successfully!',
    'updateMakerFailed': 'Failed to update maker profile',
    'saving': 'Saving...',
    'saveChanges': 'Save Changes',
    'creating': 'Creating...',
    'create': 'Create',
    'totalVideos': 'Total Videos',
    'totalProducts': 'Total Products',
    'totalViews': 'Total Views',
    'totalLikes': 'Total Likes',
    'featuredMakersTitle': 'Featured Makers of the Week',
    'featuredMakerName1': 'Lina Chen',
    'featuredMakerBio1': 'A textile artist from Yunnan using natural dyes to weave cozy shawls.',
    'featuredMakerName2': 'Maya Wang',
    'featuredMakerBio2': 'Blending traditional ceramics with modern forms to craft warm tea sets.',
    'featuredMakerName3': 'Hao Liu',
    'featuredMakerBio3': 'A fourth-generation bamboo artisan creating sustainable home décor.',
    'latestProductsTitle': 'Latest from Our Community',
    'mockProductName1': 'Artisan Tea Set',
    'mockProductDescription1': 'Hand-thrown ceramic tea set perfect for daily rituals.',
    'mockProductCategory1': 'Tea',
    'mockProductName2': 'Handwoven Tote',
    'mockProductDescription2': 'Lightweight and sturdy tote that carries a touch of nature.',
    'mockProductCategory2': 'Accessories',
    'mockProductName3': 'Bamboo Night Lamp',
    'mockProductDescription3': 'Soft ambient light and bamboo patterns for a calming corner.',
    'mockProductCategory3': 'Home',
    'mockProductName4': 'Hand-Painted Tea Cups',
    'mockProductDescription4': 'Each cup features a unique hand-painted motif for collectors.',
    'mockProductCategory4': 'Ceramics',
    'howItWorksTitle': 'Discover. Connect. Support.',
    'howItWorksStep1Title': '1. Discover authentic stories',
    'howItWorksStep1Description': 'Learn the journey behind every product and the maker who created it.',
    'howItWorksStep2Title': '2. Connect directly with makers',
    'howItWorksStep2Description': 'Chat about custom requests or collaborations inside the platform.',
    'howItWorksStep3Title': '3. Support sustainable creativity',
    'howItWorksStep3Description': 'Your purchase keeps independent makers crafting meaningful goods.',
    'ctaHeadline': 'Are you a maker? Join our community.',
    'ctaButtonText': 'Learn More',
    'productsPageTitle': 'All Products',
    'productsFilterCategoriesTitle': 'Categories',
    'productsFilterCategoryApparel': 'Apparel',
    'productsFilterCategoryHomeDecor': 'Home Decor',
    'productsFilterCategoryAccessories': 'Accessories',
    'productsFilterPriceTitle': 'Price Range',
    'productsFilterPricePlaceholder': 'Price slider coming soon',
    'productsFilterMakersTitle': 'Makers',
    'productsFilterMakerA': 'Maker A',
    'productsFilterMakerB': 'Maker B',
    'productsFilterMakerC': 'Maker C',
    'productDetailBy': 'By',
    'productDetailPlaceholderMaker': 'Maker Lina',
    'productDetailPlaceholderTitle': 'Handwoven Bamboo Lamp',
    'productDetailPlaceholderPrice': '$129',
    'productDetailQuantity': 'Quantity',
    'productDetailAddToCart': 'Add to Cart',
    'productDetailStoryTitle': 'Product Story',
    'productDetailStoryParagraph1': 'Crafted by Lina in the Yunnan mountains, this piece blends traditional bamboo weaving with a modern silhouette to warm any room.',
    'productDetailStoryParagraph2': 'Each strand of bamboo is carefully selected, cleaned, and steamed to retain its flexibility and natural hue before being woven by hand.',
    'productDetailStoryParagraph3': 'When lit, the lamp casts gentle patterns that create a calming atmosphere — perfect for a living room corner or bedside table.',
    'makerCoverAlt': 'Maker cover photo',
    'makerProfilePlaceholderName': 'Zhang Wei',
    'makerProfilePlaceholderBio': 'Woodworker from Yunnan Province crafting stories in grain.',
    'makerFollowButton': 'Follow',
    'makerStoryTitle': 'My Story',
    'makerStoryParagraph1': 'I grew up in a small village in Yunnan, learning woodworking from my grandfather. Every grain of wood feels like poetry from nature.',
    'makerStoryParagraph2': 'I source timber carefully, working with local communities to ensure sustainable origins. Each piece is hand-finished to preserve the warmth of wood.',
    'makerStoryParagraph3': 'My hope is to bring calm into modern homes and inspire more young makers to embrace the craft.',
    'makerCreationsTitle': 'My Creations',
    // Register page translations
    'registerTitle': 'Create New Account',
    'registerSubtitle': 'Already have an account?',
    'registerLoginLink': 'Log In',
    'registerNameLabel': 'Name (Optional)',
    'registerNamePlaceholder': 'Your name',
    'registerEmailLabel': 'Email',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'Password',
    'registerPasswordPlaceholder': 'At least 6 characters',
    'registerConfirmPasswordLabel': 'Confirm Password',
    'registerConfirmPasswordPlaceholder': 'Re-enter your password',
    'registerButton': 'Create Account',
    'registerButtonLoading': 'Signing up...',
    'registerButtonSuccess': 'Signed up!',
    'registerSuccessMessage': 'Account created successfully! Redirecting...',
    'registerPasswordMismatch': 'Passwords do not match',
    'registerPasswordTooShort': 'Password must be at least 6 characters',
    'registerError': 'Registration failed, please try again',
    'registerGoogleError': 'Failed to start Google signup',
    'registerOr': 'Or',
    'registerGoogleButton': 'Sign up with Google',
    'assistants': 'Assistants',
    'assistantsCenter': 'Assistants Center',
    'checkoutCartInvalid': 'Some items in your cart are invalid. Please refresh and try again.',
    'checkoutPhoneInvalid': 'Please enter a valid phone number.',
    'checkoutErrorGeneric': 'Unable to create order. Please try again.',
    'checkoutErrorValidation': 'Invalid order data. Please check your cart and shipping information.',
    'checkoutErrorAuth': 'Please log in to complete your order.',
    'checkoutErrorForbidden': 'You do not have permission to create this order.',
    'checkoutErrorConflict': 'This order conflicts with existing data. Please refresh and try again.',
    'checkoutErrorServer': 'Server error. Please try again later.',
  },
};

export const LanguageProvider: React.FC<{ 
  children: React.ReactNode;
  initialLocale?: Language;
}> = ({ children, initialLocale }) => {
  // Initialize with initialLocale if provided, otherwise default to 'zh'
  // This is safe because useState only runs on client-side after hydration
  const [language, setLanguageState] = useState<Language>(initialLocale || 'zh');

  useEffect(() => {
    // Only run in browser (client-side)
    if (typeof window === 'undefined') {
      return;
    }

    try {
      // If initialLocale is provided, use it and save to localStorage
      if (initialLocale && (initialLocale === 'zh' || initialLocale === 'ar' || initialLocale === 'en')) {
        setLanguageState(initialLocale);
        localStorage.setItem('language', initialLocale);
        return;
      }
      
      // Otherwise, load language from localStorage
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'ar' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      // localStorage may not be available (private browsing, etc.)
      // Silently fail and use default language
      console.warn('Failed to access localStorage in LanguageProvider:', error);
    }
  }, [initialLocale]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Only save to localStorage in browser
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('language', lang);
      } catch (error) {
        // localStorage may not be available - ignore
        console.warn('Failed to save language to localStorage:', error);
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Default context value used during prerendering or when no provider is present
const defaultLanguageContext: LanguageContextType = {
  language: 'en',
  setLanguage: () => {
    // No-op function for default context
  },
  t: (key: string) => key,
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Fallback used during prerendering or when no provider is present
    return defaultLanguageContext;
  }
  return context;
};

