'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  zh: {
    'home': '首页',
    'shortVideos': '短视频',
    'longVideos': '长视频',
    'products': '商品',
    'search': '搜索',
    'chat': '聊天',
    'feed': '动态',
    'uploadVideo': '上传视频',
    'addProduct': '添加商品',
    'login': '登录',
    'register': '注册',
    'logout': '退出',
    'myAccount': '我的账户',
    'loading': '加载中...',
    'error': '错误',
    'retry': '重试',
    'noContent': '暂无内容',
    'viewMore': '查看更多',
    'welcome': '欢迎来到 Panda Chao',
    'subtitle': '结合社交媒体与电子商务的创新平台',
    'subtitle2': '分享视频，展示产品，连接世界',
    'watchShortVideos': '观看短视频',
    'browseProducts': '浏览商品',
    'hotShortVideos': '热门短视频',
    'featuredLongVideos': '精选长视频',
    'recommendedProducts': '推荐商品',
    'language': '语言',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': '为世界上的创作者打造的中立平台',
    'discover': '探索',
    'aboutPandaChao': '关于 Panda Chao',
    'whySell': '为什么选择我们？',
    'creatorStories': '创作者故事',
    'faq': '常见问题',
    'communityServices': '社区与服务',
    'servicesMarketplace': '服务市场',
    'becomeServiceProvider': '成为服务提供者',
    'blog': '博客',
    'contact': '联系我们',
    'toolsLanguages': '工具与语言',
    'languageSwitcher': '切换语言',
    'currencySwitcher': '货币',
    'appComingSoon': '应用商店图标即将上线',
    'rightsReserved': '© 2025 Panda Chao. 版权所有。',
    'terms': '服务条款',
    'privacy': '隐私政策',
    'homeHeroHeadline': '手作故事，真心好物。',
    'homeHeroDescription': '来自手工匠人的真实创作故事，感受独一无二的温度。',
    'homeHeroTitle': '手作故事，真心好物。',
    'featuredMakers': '本周精选匠人',
    'featuredProducts': '社区最新上架',
    'featuredVideos': '精选视频',
    'viewAll': '查看更多',
    'founderSectionTitle': '创始人控制中心',
    'founderSectionDescription': '为创始人：6个专业AI助手帮助您进行战略决策、技术、安全、商务、内容和物流。',
    'goToFounderConsole': '前往创始人控制台',
    'homeHeroCTA': '探索商品',
    'featuredMakersTitle': '本周精选匠人',
    'featuredMakerName1': '陈素素',
    'featuredMakerBio1': '来自云南山区的手工艺人，以天然植物染织手工披肩。',
    'featuredMakerName2': '王小梅',
    'featuredMakerBio2': '将传统陶艺与现代审美结合，打造温润的日常茶具。',
    'featuredMakerName3': '刘海涛',
    'featuredMakerBio3': '竹编第四代传承人，创作可持续的生活家居。',
    'latestProductsTitle': '社区最新上架',
    'mockProductName1': '匠心茶具套装',
    'mockProductDescription1': '手工拉坯烧制的茶具，适合日常品茗与待客。',
    'mockProductCategory1': '茶具',
    'mockProductName2': '手织藤编托特包',
    'mockProductDescription2': '轻盈又结实的手工托特包，带来自然气息。',
    'mockProductCategory2': '配饰',
    'mockProductName3': '竹制静夜台灯',
    'mockProductDescription3': '柔和灯光配合竹编纹理，营造温暖空间。',
    'mockProductCategory3': '家居',
    'mockProductName4': '手绘陶瓷茶杯',
    'mockProductDescription4': '每只杯子都带有独特的手绘图案，适合收藏。',
    'mockProductCategory4': '陶瓷',
    'howItWorksTitle': '发现・连接・支持',
    'howItWorksStep1Title': '1. 发现真实故事',
    'howItWorksStep1Description': '浏览匠人的创作历程与灵感来源，了解每件作品的背景。',
    'howItWorksStep2Title': '2. 直接联系创作者',
    'howItWorksStep2Description': '通过平台与创作者交流，提出定制需求或合作想法。',
    'howItWorksStep3Title': '3. 支持可持续创作',
    'howItWorksStep3Description': '购买带着温度的作品，让匠人持续创作更多好物。',
    'ctaHeadline': '你也是匠人吗？加入我们的社区。',
    'ctaButtonText': '了解更多',
    'productsPageTitle': '全部商品',
    'productsFilterCategoriesTitle': '分类',
    'productsFilterCategoryApparel': '服饰',
    'productsFilterCategoryHomeDecor': '家居装饰',
    'productsFilterCategoryAccessories': '配饰',
    'productsFilterPriceTitle': '价格区间',
    'productsFilterPricePlaceholder': '价格滑块即将上线',
    'productsFilterMakersTitle': '匠人',
    'productsFilterMakerA': '匠人 A',
    'productsFilterMakerB': '匠人 B',
    'productsFilterMakerC': '匠人 C',
    'productDetailBy': '来自',
    'productDetailPlaceholderMaker': '手工匠人 李娜',
    'productDetailPlaceholderTitle': '手工编织竹制灯具',
    'productDetailPlaceholderPrice': '¥329',
    'productDetailQuantity': '数量',
    'productDetailAddToCart': '加入购物车',
    'productDetailStoryTitle': '作品故事',
    'productDetailStoryParagraph1': '这件作品来自云南山区的匠人李娜，融合传统竹编技艺与现代生活美学。每一道纹理都由手工完成，保持竹材的自然韵味。',
    'productDetailStoryParagraph2': '制作过程中，匠人会精心挑选竹材，进行清洗、晾晒和蒸汽定型，确保灯具在使用时稳定耐用，同时保留竹材的原色。',
    'productDetailStoryParagraph3': '灯光透过竹编的纹理，在夜晚为空间带来温暖而宁静的光影，适合放置在卧室、书房或客厅角落，营造舒缓氛围。',
    'makerCoverAlt': '匠人主页封面图',
    'makerProfilePlaceholderName': '张伟',
    'makerProfilePlaceholderBio': '来自云南的木工匠人，用温暖木纹讲述家的故事。',
    'makerFollowButton': '关注',
    'makerStoryTitle': '我的故事',
    'makerStoryParagraph1': '我出生在云南的一个小山村，从小跟随外公学习木工。木头的纹理就像自然写下的诗，每一件作品都有独特的生命力。',
    'makerStoryParagraph2': '为了寻找最适合的木材，我常常深入山林，与当地村民交流，确保每块木头都来自可持续来源。制作过程中，我坚持手工打磨，只为保留木头的温润触感。',
    'makerStoryParagraph3': '我希望通过这些作品，让更多人感受到慢生活的温度，也希望支持更多年轻人加入到手工匠人的队伍中。',
    'makerCreationsTitle': '我的作品',
    // Register page translations
    'registerTitle': '创建新账户',
    'registerSubtitle': '已有账户？',
    'registerLoginLink': '登录',
    'registerNameLabel': '姓名（可选）',
    'registerNamePlaceholder': '您的姓名',
    'registerEmailLabel': '电子邮箱',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': '密码',
    'registerPasswordPlaceholder': '至少6个字符',
    'registerConfirmPasswordLabel': '确认密码',
    'registerConfirmPasswordPlaceholder': '请再次输入密码',
    'registerButton': '创建账户',
    'registerButtonLoading': '注册中...',
    'registerButtonSuccess': '注册成功！',
    'registerSuccessMessage': '账户创建成功！正在跳转...',
    'registerPasswordMismatch': '密码不匹配',
    'registerPasswordTooShort': '密码至少需要6个字符',
    'registerError': '注册失败，请重试',
    'registerGoogleError': 'Google注册失败',
    'registerOr': '或',
    'registerGoogleButton': '使用Google注册',
  },
  ar: {
    'home': 'الرئيسية',
    'shortVideos': 'فيديوهات قصيرة',
    'longVideos': 'فيديوهات طويلة',
    'products': 'المنتجات',
    'search': 'البحث',
    'chat': 'الدردشة',
    'feed': 'المنشورات',
    'uploadVideo': 'رفع فيديو',
    'addProduct': 'إضافة منتج',
    'login': 'تسجيل الدخول',
    'register': 'التسجيل',
    'logout': 'تسجيل الخروج',
    'myAccount': 'حسابي',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'retry': 'إعادة المحاولة',
    'noContent': 'لا يوجد محتوى',
    'viewMore': 'عرض المزيد',
    'welcome': 'مرحباً بك في Panda Chao',
    'subtitle': 'منصة مبتكرة تجمع بين التواصل الاجتماعي والتجارة الإلكترونية',
    'subtitle2': 'شارك الفيديوهات، اعرض المنتجات، واتصل بالعالم',
    'watchShortVideos': 'مشاهدة الفيديوهات القصيرة',
    'browseProducts': 'تصفح المنتجات',
    'hotShortVideos': 'الفيديوهات القصيرة الشائعة',
    'featuredLongVideos': 'الفيديوهات الطويلة المميزة',
    'recommendedProducts': 'المنتجات الموصى بها',
    'language': 'اللغة',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'منصة محايدة لدعم صنّاع المحتوى حول العالم',
    'discover': 'استكشف',
    'aboutPandaChao': 'عن Panda Chao',
    'whySell': 'لماذا البيع معنا؟',
    'creatorStories': 'قصص المبدعين',
    'faq': 'الأسئلة الشائعة',
    'communityServices': 'المجتمع والخدمات',
    'servicesMarketplace': 'سوق الخدمات',
    'becomeServiceProvider': 'انضم كمقدم خدمة',
    'blog': 'المدونة',
    'contact': 'تواصل معنا',
    'toolsLanguages': 'الأدوات واللغات',
    'languageSwitcher': 'اختر اللغة',
    'currencySwitcher': 'العملة',
    'appComingSoon': 'أيقونات المتاجر قادمة قريباً',
    'rightsReserved': '© 2025 Panda Chao. جميع الحقوق محفوظة.',
    'terms': 'شروط الخدمة',
    'privacy': 'سياسة الخصوصية',
    'homeHeroHeadline': 'حكايات مصنوعة باليد. منتجات بنبض القلب.',
    'homeHeroDescription': 'اكتشف قصص الحرفيين الحقيقيين وادعم أعمالهم الأصيلة.',
    'homeHeroTitle': 'حكايات مصنوعة باليد. منتجات بنبض القلب.',
    'featuredMakers': 'حرفيون مميزون',
    'featuredProducts': 'منتجات مميزة',
    'featuredVideos': 'فيديوهات مميزة',
    'viewAll': 'عرض الكل',
    'founderSectionTitle': 'مركز القيادة للمؤسس',
    'founderSectionDescription': 'للمؤسس: 6 مساعدين ذكاء اصطناعي متخصصين يساعدونك في القرارات الاستراتيجية، التقنية، الأمان، التجارة، المحتوى، واللوجستيات',
    'goToFounderConsole': 'اذهب إلى مركز المؤسس',
    'homeHeroCTA': 'استكشف المنتجات',
    'featuredMakersTitle': 'صنّاع الأسبوع المميزون',
    'featuredMakerName1': 'ليلى تشين',
    'featuredMakerBio1': 'حرفية من جبال يونّان تستخدم أصباغاً نباتية لصنع شالات منسوجة يدوياً.',
    'featuredMakerName2': 'مريم وانغ',
    'featuredMakerBio2': 'تمزج بين الفخار التقليدي واللمسات العصرية لتقديم أطقم شاي دافئة.',
    'featuredMakerName3': 'هاو ليو',
    'featuredMakerBio3': 'حرفي في الجيل الرابع لفن الخيزران يصنع ديكوراً منزلياً مستداماً.',
    'latestProductsTitle': 'أحدث ما في مجتمعنا',
    'mockProductName1': 'طقم شاي حرفي',
    'mockProductDescription1': 'طقم شاي مصنوع يدوياً من الخزف المتين يناسب الجلسات اليومية.',
    'mockProductCategory1': 'الشاي',
    'mockProductName2': 'حقيبة توت منسوجة',
    'mockProductDescription2': 'حقيبة خفيفة ومتانة عالية تمنحك لمسة طبيعية.',
    'mockProductCategory2': 'إكسسوارات',
    'mockProductName3': 'مصباح خيزران هادئ',
    'mockProductDescription3': 'إضاءة ناعمة مع زخارف من الخيزران تزيد دفء المساحة.',
    'mockProductCategory3': 'ديكور منزلي',
    'mockProductName4': 'أكواب شاي مزخرفة',
    'mockProductDescription4': 'كل كوب يحمل رسماً فريداً باليد ليكون إضافة مميزة.',
    'mockProductCategory4': 'خزف',
    'howItWorksTitle': 'اكتشف. تواصل. ادعم.',
    'howItWorksStep1Title': '1. اكتشف القصص الأصيلة',
    'howItWorksStep1Description': 'تعرّف على رحلة كل صانع ومصدر إلهامه وراء كل منتج.',
    'howItWorksStep2Title': '2. تواصل مباشرة مع الصنّاع',
    'howItWorksStep2Description': 'ناقش الأفكار واطلب التصاميم الخاصة عبر منصتنا.',
    'howItWorksStep3Title': '3. ادعم الإبداع المستدام',
    'howItWorksStep3Description': 'بشرائك تساعد الصنّاع على الاستمرار في تقديم أعمال ذات قيمة.',
    'ctaHeadline': 'هل أنت صانع؟ انضم إلى مجتمعنا الآن.',
    'ctaButtonText': 'اعرف المزيد',
    'productsPageTitle': 'جميع المنتجات',
    'productsFilterCategoriesTitle': 'الفئات',
    'productsFilterCategoryApparel': 'الملابس',
    'productsFilterCategoryHomeDecor': 'ديكور المنزل',
    'productsFilterCategoryAccessories': 'الإكسسوارات',
    'productsFilterPriceTitle': 'نطاق السعر',
    'productsFilterPricePlaceholder': 'شريط السعر سيظهر هنا قريباً',
    'productsFilterMakersTitle': 'الصنّاع',
    'productsFilterMakerA': 'الصانع أ',
    'productsFilterMakerB': 'الصانع ب',
    'productsFilterMakerC': 'الصانع ج',
    'productDetailBy': 'بواسطة',
    'productDetailPlaceholderMaker': 'الحرفية ليلى',
    'productDetailPlaceholderTitle': 'مصباح خيزران منسوج يدويًا',
    'productDetailPlaceholderPrice': '329 درهم',
    'productDetailQuantity': 'الكمية',
    'productDetailAddToCart': 'أضف إلى السلة',
    'productDetailStoryTitle': 'قصة المنتج',
    'productDetailStoryParagraph1': 'هذا المنتج من صنع الحرفية ليلى في جبال يونّان، حيث تمزج بين فن الخيزران التقليدي واللمسات المعاصرة لتقديم قطعة مميزة للمنزل.',
    'productDetailStoryParagraph2': 'تبدأ عملية التصنيع باختيار أعواد الخيزران بعناية، ثم تنظيفها وتجفيفها ومعالجتها بالبخار للحفاظ على متانتها وجمالها الطبيعي.',
    'productDetailStoryParagraph3': 'عند إضاءة المصباح تنعكس الظلال الناعمة على الجدران، ما يخلق أجواء دافئة وهادئة مثالية لغرفة المعيشة أو الزاوية المفضلة لديك.',
    'makerCoverAlt': 'صورة الغلاف لصانع المحتوى',
    'makerProfilePlaceholderName': 'تشانغ وي',
    'makerProfilePlaceholderBio': 'نجار من مقاطعة يونّان يصنع قصصًا دافئة من الخشب.',
    'makerFollowButton': 'متابعة',
    'makerStoryTitle': 'قصتي',
    'makerStoryParagraph1': 'ولدتُ في قرية صغيرة في يونّان وتعلمت النجارة على يد جدي. أرى عروق الخشب كشعر طبيعي يحمل حياةً خاصة بكل قطعة أصنعها.',
    'makerStoryParagraph2': 'أبحث دائمًا عن أفضل أنواع الخشب من مصادر مستدامة، وأعالج كل قطعة بعناية حتى أحافظ على ملمسها الدافئ وطابعها الأصلي.',
    'makerStoryParagraph3': 'أطمح أن تمنح منتجاتي إحساسًا بالسكينة لكل منزل، وأن أشجع المزيد من الشباب على الانضمام إلى عالم الحرف اليدوية.',
    'makerCreationsTitle': 'إبداعاتي',
    // Register page translations (Arabic - kept for future use)
    'registerTitle': 'إنشاء حساب جديد',
    'registerSubtitle': 'لديك حساب بالفعل؟',
    'registerLoginLink': 'تسجيل الدخول',
    'registerNameLabel': 'الاسم (اختياري)',
    'registerNamePlaceholder': 'اسمك',
    'registerEmailLabel': 'البريد الإلكتروني',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'كلمة المرور',
    'registerPasswordPlaceholder': '6 أحرف على الأقل',
    'registerConfirmPasswordLabel': 'تأكيد كلمة المرور',
    'registerConfirmPasswordPlaceholder': 'أعد إدخال كلمة المرور',
    'registerButton': 'إنشاء الحساب',
    'registerButtonLoading': 'جاري التسجيل...',
    'registerButtonSuccess': 'تم التسجيل!',
    'registerSuccessMessage': 'تم إنشاء الحساب بنجاح! جاري التوجيه...',
    'registerPasswordMismatch': 'كلمات المرور غير متطابقة',
    'registerPasswordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'registerError': 'فشل التسجيل، يرجى المحاولة مرة أخرى',
    'registerGoogleError': 'فشل في بدء التسجيل عبر Google',
    'registerOr': 'أو',
    'registerGoogleButton': 'التسجيل بواسطة Google',
  },
  en: {
    'home': 'Home',
    'shortVideos': 'Short Videos',
    'longVideos': 'Long Videos',
    'products': 'Products',
    'search': 'Search',
    'chat': 'Chat',
    'feed': 'Feed',
    'uploadVideo': 'Upload Video',
    'addProduct': 'Add Product',
    'login': 'Log In',
    'register': 'Sign Up',
    'logout': 'Log Out',
    'myAccount': 'My Account',
    'loading': 'Loading...',
    'error': 'Error',
    'retry': 'Retry',
    'noContent': 'No content available',
    'viewMore': 'View more',
    'welcome': 'Welcome to Panda Chao',
    'subtitle': 'An innovative platform that blends social media and commerce',
    'subtitle2': 'Share stories, showcase products, connect globally',
    'watchShortVideos': 'Watch short videos',
    'browseProducts': 'Browse products',
    'hotShortVideos': 'Trending short videos',
    'featuredLongVideos': 'Featured long videos',
    'recommendedProducts': 'Recommended products',
    'language': 'Language',
    'chinese': '中文',
    'arabic': 'العربية',
    'english': 'English',
    'footerTagline': 'A neutral platform for makers to reach the world',
    'discover': 'Discover',
    'aboutPandaChao': 'About Panda Chao',
    'whySell': 'Why sell with us?',
    'creatorStories': 'Creator stories',
    'faq': 'FAQ',
    'communityServices': 'Community & Services',
    'servicesMarketplace': 'Services marketplace',
    'becomeServiceProvider': 'Become a service provider',
    'blog': 'Blog',
    'contact': 'Contact us',
    'toolsLanguages': 'Tools & Languages',
    'languageSwitcher': 'Switch language',
    'currencySwitcher': 'Currency',
    'appComingSoon': 'App store links coming soon',
    'rightsReserved': '© 2025 Panda Chao. All rights reserved.',
    'terms': 'Terms of Service',
    'privacy': 'Privacy Policy',
    'homeHeroHeadline': 'Stories Made by Hand. Products Made with Heart.',
    'homeHeroDescription': 'Meet inspiring makers and explore the handcrafted goods they bring to life.',
    'homeHeroTitle': 'Stories Made by Hand. Products Made with Heart.',
    'featuredMakers': 'Featured Makers',
    'featuredProducts': 'Featured Products',
    'featuredVideos': 'Featured Videos',
    'viewAll': 'View All',
    'founderSectionTitle': 'Founder Command Center',
    'founderSectionDescription': 'For Founders: 6 specialized AI assistants help you with strategic decisions, technology, security, commerce, content, and logistics.',
    'goToFounderConsole': 'Go to Founder Console',
    'homeHeroCTA': 'Explore Products',
    'featuredMakersTitle': 'Featured Makers of the Week',
    'featuredMakerName1': 'Lina Chen',
    'featuredMakerBio1': 'A textile artist from Yunnan using natural dyes to weave cozy shawls.',
    'featuredMakerName2': 'Maya Wang',
    'featuredMakerBio2': 'Blending traditional ceramics with modern forms to craft warm tea sets.',
    'featuredMakerName3': 'Hao Liu',
    'featuredMakerBio3': 'A fourth-generation bamboo artisan creating sustainable home décor.',
    'latestProductsTitle': 'Latest from Our Community',
    'mockProductName1': 'Artisan Tea Set',
    'mockProductDescription1': 'Hand-thrown ceramic tea set perfect for daily rituals.',
    'mockProductCategory1': 'Tea',
    'mockProductName2': 'Handwoven Tote',
    'mockProductDescription2': 'Lightweight and sturdy tote that carries a touch of nature.',
    'mockProductCategory2': 'Accessories',
    'mockProductName3': 'Bamboo Night Lamp',
    'mockProductDescription3': 'Soft ambient light and bamboo patterns for a calming corner.',
    'mockProductCategory3': 'Home',
    'mockProductName4': 'Hand-Painted Tea Cups',
    'mockProductDescription4': 'Each cup features a unique hand-painted motif for collectors.',
    'mockProductCategory4': 'Ceramics',
    'howItWorksTitle': 'Discover. Connect. Support.',
    'howItWorksStep1Title': '1. Discover authentic stories',
    'howItWorksStep1Description': 'Learn the journey behind every product and the maker who created it.',
    'howItWorksStep2Title': '2. Connect directly with makers',
    'howItWorksStep2Description': 'Chat about custom requests or collaborations inside the platform.',
    'howItWorksStep3Title': '3. Support sustainable creativity',
    'howItWorksStep3Description': 'Your purchase keeps independent makers crafting meaningful goods.',
    'ctaHeadline': 'Are you a maker? Join our community.',
    'ctaButtonText': 'Learn More',
    'productsPageTitle': 'All Products',
    'productsFilterCategoriesTitle': 'Categories',
    'productsFilterCategoryApparel': 'Apparel',
    'productsFilterCategoryHomeDecor': 'Home Decor',
    'productsFilterCategoryAccessories': 'Accessories',
    'productsFilterPriceTitle': 'Price Range',
    'productsFilterPricePlaceholder': 'Price slider coming soon',
    'productsFilterMakersTitle': 'Makers',
    'productsFilterMakerA': 'Maker A',
    'productsFilterMakerB': 'Maker B',
    'productsFilterMakerC': 'Maker C',
    'productDetailBy': 'By',
    'productDetailPlaceholderMaker': 'Maker Lina',
    'productDetailPlaceholderTitle': 'Handwoven Bamboo Lamp',
    'productDetailPlaceholderPrice': '$129',
    'productDetailQuantity': 'Quantity',
    'productDetailAddToCart': 'Add to Cart',
    'productDetailStoryTitle': 'Product Story',
    'productDetailStoryParagraph1': 'Crafted by Lina in the Yunnan mountains, this piece blends traditional bamboo weaving with a modern silhouette to warm any room.',
    'productDetailStoryParagraph2': 'Each strand of bamboo is carefully selected, cleaned, and steamed to retain its flexibility and natural hue before being woven by hand.',
    'productDetailStoryParagraph3': 'When lit, the lamp casts gentle patterns that create a calming atmosphere — perfect for a living room corner or bedside table.',
    'makerCoverAlt': 'Maker cover photo',
    'makerProfilePlaceholderName': 'Zhang Wei',
    'makerProfilePlaceholderBio': 'Woodworker from Yunnan Province crafting stories in grain.',
    'makerFollowButton': 'Follow',
    'makerStoryTitle': 'My Story',
    'makerStoryParagraph1': 'I grew up in a small village in Yunnan, learning woodworking from my grandfather. Every grain of wood feels like poetry from nature.',
    'makerStoryParagraph2': 'I source timber carefully, working with local communities to ensure sustainable origins. Each piece is hand-finished to preserve the warmth of wood.',
    'makerStoryParagraph3': 'My hope is to bring calm into modern homes and inspire more young makers to embrace the craft.',
    'makerCreationsTitle': 'My Creations',
    // Register page translations
    'registerTitle': 'Create New Account',
    'registerSubtitle': 'Already have an account?',
    'registerLoginLink': 'Log In',
    'registerNameLabel': 'Name (Optional)',
    'registerNamePlaceholder': 'Your name',
    'registerEmailLabel': 'Email',
    'registerEmailPlaceholder': 'example@email.com',
    'registerPasswordLabel': 'Password',
    'registerPasswordPlaceholder': 'At least 6 characters',
    'registerConfirmPasswordLabel': 'Confirm Password',
    'registerConfirmPasswordPlaceholder': 'Re-enter your password',
    'registerButton': 'Create Account',
    'registerButtonLoading': 'Signing up...',
    'registerButtonSuccess': 'Signed up!',
    'registerSuccessMessage': 'Account created successfully! Redirecting...',
    'registerPasswordMismatch': 'Passwords do not match',
    'registerPasswordTooShort': 'Password must be at least 6 characters',
    'registerError': 'Registration failed, please try again',
    'registerGoogleError': 'Failed to start Google signup',
    'registerOr': 'Or',
    'registerGoogleButton': 'Sign up with Google',
  },
};

export const LanguageProvider: React.FC<{ 
  children: React.ReactNode;
  initialLocale?: Language;
}> = ({ children, initialLocale }) => {
  // Initialize with initialLocale if provided, otherwise default to 'zh'
  // This is safe because useState only runs on client-side after hydration
  const [language, setLanguageState] = useState<Language>(initialLocale || 'zh');

  useEffect(() => {
    // Only run in browser (client-side)
    if (typeof window === 'undefined') {
      return;
    }

    try {
      // If initialLocale is provided, use it and save to localStorage
      if (initialLocale && (initialLocale === 'zh' || initialLocale === 'ar' || initialLocale === 'en')) {
        setLanguageState(initialLocale);
        localStorage.setItem('language', initialLocale);
        return;
      }
      
      // Otherwise, load language from localStorage
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'ar' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      // localStorage may not be available (private browsing, etc.)
      // Silently fail and use default language
      console.warn('Failed to access localStorage in LanguageProvider:', error);
    }
  }, [initialLocale]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Only save to localStorage in browser
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('language', lang);
      } catch (error) {
        // localStorage may not be available - ignore
        console.warn('Failed to save language to localStorage:', error);
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

